Add project tech detection test

diff --git a/actions/check-artifact-version/action.yml b/actions/check-artifact-version/action.yml
--- a/actions/check-artifact-version/action.yml
+++ b/actions/check-artifact-version/action.yml
@@ -45,5 +45,5 @@ runs:
       shell: ${{ inputs.shell }}
       working-directory: ${{ inputs.project-directory }}
       run: |
-        echo "❌Cannot validate the artifact version for an unknown project type"
+        echo "❌Cannot validate the artifact version for an unknown project type" >&2
         exit 1
diff --git a/actions/print-rust-info/action.yml b/actions/print-rust-info/action.yml
--- a/actions/print-rust-info/action.yml
+++ b/actions/print-rust-info/action.yml
@@ -23,7 +23,7 @@ runs:
 
         if [[ ! -f $toolchainFile ]]
         then
-          echo "Missing toolchain file: '$toolchainFile'"
+          echo "❌Missing toolchain file: '$toolchainFile'" >&2
           exit 1
         fi
 
