Update documentation

diff --git a/actions/check-artifact-version/action.yml b/actions/check-artifact-version/action.yml
--- a/actions/check-artifact-version/action.yml
+++ b/actions/check-artifact-version/action.yml
@@ -15,7 +15,7 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Detect project type
+    - name: Detect project tech
       id: detect-project-tech
       uses: giancosta86/aurora-github/detect-project-tech@b2.0.0
       with:
@@ -45,5 +45,5 @@ runs:
       shell: ${{ inputs.shell }}
       working-directory: ${{ inputs.project-directory }}
       run: |
-        echo "❌Cannot validate the artifact version for an unknown project type" >&2
+        echo "❌Cannot validate the artifact version for an unknown project tech" >&2
         exit 1
