Enforce stricter input checks for several actions

diff --git a/actions/publish-github-pages/action.yml b/actions/publish-github-pages/action.yml
--- a/actions/publish-github-pages/action.yml
+++ b/actions/publish-github-pages/action.yml
@@ -29,15 +29,15 @@ runs:
     - name: Validate inputs
       shell: bash
       run: |
-        if [[ -z "${{ inputs.source-directory }}" ]]
-        then
-          echo "❌Missing action input: 'source-directory'!" >&2
-          exit 1
-        fi
-
         if [[ -z "${{ inputs.optional }}" ]]
         then
           echo "❌Missing action input: 'optional'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.enforce-branch-version }}" ]]
+        then
+          echo "❌Missing action input: 'enforce-branch-version'!" >&2
           exit 1
         fi
 
diff --git a/actions/publish-npm-package/action.yml b/actions/publish-npm-package/action.yml
--- a/actions/publish-npm-package/action.yml
+++ b/actions/publish-npm-package/action.yml
@@ -40,6 +40,18 @@ runs:
           exit 1
         fi
 
+        if [[ -z "${{ inputs.website-directory }}" ]]
+        then
+          echo "❌Missing action input: 'website-directory'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.enforce-branch-version }}" ]]
+        then
+          echo "❌Missing action input: 'enforce-branch-version'!" >&2
+          exit 1
+        fi
+
         if [[ ! -f "package.json" ]]
         then
           echo "❌The package.json descriptor file does not exist!!" >&2
diff --git a/actions/verify-npm-package/action.yml b/actions/verify-npm-package/action.yml
--- a/actions/verify-npm-package/action.yml
+++ b/actions/verify-npm-package/action.yml
@@ -45,6 +45,12 @@ runs:
           exit 1
         fi
 
+        if [[ -z "${{ inputs.enforce-branch-version }}" ]]
+        then
+          echo "❌Missing action input: 'enforce-branch-version'!" >&2
+          exit 1
+        fi
+
         if [[ -z "${{ inputs.enforce-esm }}" ]]
         then
           echo "❌Missing action input: 'enforce-esm'!" >&2
