Introduce v6.0.0 (#16)
* In `verify-npm-package`, launch `check-subpath-exports` before `run-custom-tests`

* Redesign `publish-github-pages` (closes #17)

* Add `website-directory` input to `publish-npm-package`

* Add `website-directory` input to `publish-rust-crate`

* Add `website-directory` input to `publish-rust-wasm`

* Express action dependencies in the tests, too

* Remove every `registry-url` input

* Remove every `frozen-lockfile` input

* Redesign setup-nodejs-context

* Remove every `dedicated-env` and `custom-test-env` input

* Remove every `pnpm-version` input

* Remove every `shell` input

* Enhance documentation

* Remove redundant `./` from paths

* Ensure the artifact directory exists in `publish-github-pages`

* In publish- actions, only publish the website if dry-run is disabled

* Simplify inject-branch-version

* Simplify tests

* Update README

* Update the action diagram

diff --git a/actions/publish-github-pages/action.yml b/actions/publish-github-pages/action.yml
--- a/actions/publish-github-pages/action.yml
+++ b/actions/publish-github-pages/action.yml
@@ -3,12 +3,15 @@ description: Publishes a directory as the GitHub Pages website for the current r
 
 inputs:
   source-directory:
-    description: Relative directory containing the website.
-    default: website
+    description: Directory containing the website.
 
-  shell:
-    description: The shell used to run commands.
-    default: bash
+  optional:
+    description: Whether "source-directory" can be an empty string or a missing directory.
+    default: false
+
+  dry-run:
+    description: Stops the publication just before uploading.
+    default: false
 
 outputs:
   url:
@@ -18,22 +21,143 @@ outputs:
 runs:
   using: composite
   steps:
-    - name: Print description message
-      shell: ${{ inputs.shell }}
+    - name: Validate inputs
+      shell: bash
       run: |
-        echo "📦Now publishing the '${{ inputs.source-directory }}' directory to GitHub Pages..."
+        if [[ -z "${{ inputs.source-directory }}" ]]
+        then
+          echo "❌Missing action input: 'source-directory'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.optional }}" ]]
+        then
+          echo "❌Missing action input: 'optional'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.dry-run }}" ]]
+        then
+          echo "❌Missing action input: 'dry-run'!" >&2
+          exit 1
+        fi
+
+    - name: Print description message
+      shell: bash
+      run: echo "🌐Now trying to publish to GitHub Pages..."
+
+    - name: Setup environment variables
+      shell: bash
+      run: |
+        optional="${{ inputs.optional }}"
+        sourceDirectory="${{ inputs.source-directory }}"
+        strategy=exit
+
+        if [[ -z "$sourceDirectory" ]]
+        then
+          if [[ "$optional" == "true" ]]
+          then
+            echo "💬Missing action input: 'source-directory' - won't proceed"
+          else
+            echo "❌Missing action input: 'source-directory'!" >&2
+            exit 1
+          fi
+        elif [[ ! -d "$sourceDirectory" ]]
+        then
+          if [[ "$optional" == "true" ]]
+          then
+            echo "💬Missing website directory '$sourceDirectory' - can't proceed"
+          else
+            echo "❌Missing website directory '$sourceDirectory'!" >&2
+            exit 1
+          fi
+        else
+          echo "🌐Website directory '$sourceDirectory' found!"
+          strategy=detect
+        fi
+
+        echo "strategy=$strategy" >> $GITHUB_ENV
+
+    - name: Detect website technology
+      if: ${{ env.strategy == 'detect' }}
+      shell: bash
+      working-directory: ${{ inputs.source-directory }}
+      run: |
+        if [[ -f "package.json" ]]
+        then
+          strategy=nodejs
+        else
+          strategy="static-files"
+        fi
+
+        echo "strategy=$strategy" >> $GITHUB_ENV
+
+    - name: Debug publication strategy
+      shell: bash
+      run: |
+        echo "🔎Website publication strategy: '$strategy'"
+
+    - name: Setup NodeJS context
+      if: ${{ env.strategy == 'nodejs' }}
+      uses: giancosta86/aurora-github/actions/setup-nodejs-context@v6.0.0
+      with:
+        project-directory: ${{ inputs.source-directory }}
+
+    - name: Create artifacts via NodeJS
+      if: ${{ env.strategy == 'nodejs' }}
+      shell: bash
+      working-directory: ${{ inputs.source-directory }}
+      run: |
+        pnpm build
+        artifactDirectory=${{ inputs.source-directory }}/dist
+        echo "artifactDirectory=$artifactDirectory" >> $GITHUB_ENV
+
+    - name: Setup static artifacts
+      if: ${{ env.strategy == 'static-files' }}
+      shell: bash
+      run: echo "artifactDirectory=${{ inputs.source-directory }}" >> $GITHUB_ENV
+
+    - name: Check the artifact directory
+      if: ${{ env.strategy != 'exit' }}
+      shell: bash
+      run: |
+        echo "🔎Website artifact directory: '$artifactDirectory'"
+
+        if [[ -d "$artifactDirectory" ]]
+        then
+          echo "✅The artifact directory for the 🌐website exists!"
+        else
+          if [[ "$optional" == "true" ]]
+          then
+            echo "💬Missing website artifact directory - can't proceed"
+            echo "strategy=exit" >> $GITHUB_ENV
+          else
+            echo "❌Missing website artifact directory!" >&2
+            exit 1
+          fi
+        fi
+
+    - name: Prevent uploading via dry-run
+      if: ${{ env.strategy != 'exit' && inputs.dry-run == 'true' }}
+      shell: bash
+      run: |
+        echo "💭Skipping publication, as requested by dry-run."
+        echo "strategy=exit" >> $GITHUB_ENV
 
     - name: Upload website artifacts
+      if: ${{ env.strategy != 'exit' }}
       uses: actions/upload-pages-artifact@v3
       with:
-        path: ${{ inputs.source-directory }}
+        path: ${{ env.artifactDirectory }}
 
     - name: Publish website via GitHub Pages
+      if: ${{ env.strategy != 'exit' }}
       id: publish-pages
       uses: actions/deploy-pages@v4
 
     - name: Print confirmation message
-      shell: ${{ inputs.shell }}
+      if: ${{ env.strategy != 'exit' }}
+      shell: bash
       run: |
         echo "✅Publication to GitHub Pages successful!"
         echo "🌐Website: ${{ steps.publish-pages.outputs.page_url }}"
diff --git a/actions/publish-rust-wasm/action.yml b/actions/publish-rust-wasm/action.yml
--- a/actions/publish-rust-wasm/action.yml
+++ b/actions/publish-rust-wasm/action.yml
@@ -15,10 +15,6 @@ inputs:
   npm-scope:
     description: The npm package scope or "<ROOT>".
 
-  registry-url:
-    description: The URL of the npm registry.
-    default: https://registry.npmjs.org
-
   wasm-target:
     description: The target of the 'wasm-pack build' command.
     default: web
@@ -27,19 +23,20 @@ inputs:
     description: Relative directory containing the .nvmrc file.
     default: client-tests
 
+  website-directory:
+    description: Relative directory containing the project website.
+    default: website
+
   project-directory:
     description: The directory containing Cargo.toml.
     default: .
-
-  shell:
-    description: The shell used to run commands.
-    default: bash
 
 runs:
   using: composite
   steps:
     - name: Validate inputs
-      shell: ${{ inputs.shell }}
+      shell: bash
+      working-directory: ${{ inputs.project-directory }}
       run: |
         if [[ -z "${{ inputs.dry-run }}" ]]
         then
@@ -59,6 +56,12 @@ runs:
           exit 1
         fi
 
+        if [[ -z "${{ inputs.npm-scope }}" ]]
+        then
+          echo "❌Missing action input: 'npm-scope'!" >&2
+          exit 1
+        fi
+
         if [[ -z "${{ inputs.wasm-target }}" ]]
         then
           echo "❌Missing action input: 'wasm-target'!" >&2
@@ -73,18 +76,17 @@ runs:
 
     - name: Parse npm scope
       id: parse-npm-scope
-      uses: giancosta86/aurora-github/actions/parse-npm-scope@v5.0.0
+      uses: giancosta86/aurora-github/actions/parse-npm-scope@v6.0.0
       with:
         scope: ${{ inputs.npm-scope }}
 
     - name: Install wasm-pack
-      uses: giancosta86/aurora-github/actions/install-wasm-pack@v5.0.0
+      uses: giancosta86/aurora-github/actions/install-wasm-pack@v6.0.0
       with:
         wasm-pack-version: ${{ inputs.wasm-pack-version }}
-        shell: ${{ inputs.shell }}
 
     - name: Generate the NodeJS package
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
         scope="${{ steps.parse-npm-scope.outputs.actual-scope }}"
@@ -97,16 +99,14 @@ runs:
         fi
 
     - name: Copy .nvmrc to the generated NodeJS package
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: cp "${{ inputs.node-version-directory }}/.nvmrc" pkg
 
     - name: Publish NodeJS package
-      uses: giancosta86/aurora-github/actions/publish-npm-package@v5.0.0
+      uses: giancosta86/aurora-github/actions/publish-npm-package@v6.0.0
       with:
         dry-run: ${{ inputs.dry-run }}
         npm-token: ${{ inputs.npm-token }}
-        registry-url: ${{ inputs.registry-url }}
-        frozen-lockfile: false
+        website-directory: ${{ inputs.website-directory }}
         project-directory: ${{ inputs.project-directory }}/pkg
-        shell: ${{ inputs.shell }}
diff --git a/actions/run-custom-tests/action.yml b/actions/run-custom-tests/action.yml
--- a/actions/run-custom-tests/action.yml
+++ b/actions/run-custom-tests/action.yml
@@ -14,31 +14,21 @@ inputs:
     description: The shell used to run script-file.
     default: bash
 
-  dedicated-env:
-    description: Set up a context-specific, dedicated environment.
-    default: false
-
-  registry-url:
-    description: The URL of the npm registry.
-    default: https://registry.npmjs.org
-
-  frozen-lockfile:
-    description: Fail if "pnpm-lock.yaml" is missing or outdated.
-    default: true
-
   root-directory:
     description: The directory containing the tests.
-
-  shell:
-    description: The shell used to run commands.
-    default: bash
 
 runs:
   using: composite
   steps:
     - name: Detect directory existence
-      shell: ${{ inputs.shell }}
+      shell: bash
       run: |
+        if [[ -z "${{ inputs.optional }}" ]]
+        then
+          echo "❌Missing action input: 'optional'!" >&2
+          exit 1
+        fi
+
         if [[ ! -d "${{ inputs.root-directory }}" ]]
         then
           if [[ "${{ inputs.optional }}" == "true" ]]
@@ -56,7 +46,7 @@ runs:
 
     - name: Validate inputs
       if: ${{ env.strategy == 'detect' }}
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.root-directory }}
       run: |
         echo "🔬Detecting custom test strategy in directory '${{ inputs.root-directory }}'..."
@@ -67,6 +57,12 @@ runs:
         then
           echo "🐚Custom test script '$scriptFile' found!"
           strategy="script"
+
+          if [[ -z "${{ inputs.script-shell }}" ]]
+          then
+            echo "❌Missing action input: 'script-shell'!" >&2
+            exit 1
+          fi
         elif [[ -f "package.json" ]]
         then
           echo "📦package.json file found!"
@@ -92,7 +88,7 @@ runs:
 
     - name: Run script
       if: ${{ env.strategy == 'script' }}
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.root-directory }}
       run: |
         echo "🐚Now running the custom script '${{ inputs.script-file }}'..."
@@ -100,43 +96,40 @@ runs:
         "${{ inputs.script-shell }}" "${{ inputs.script-file }}"
 
     - name: Setup NodeJS context
-      if: ${{ env.strategy == 'nodejs' && inputs.dedicated-env == 'true' }}
-      uses: giancosta86/aurora-github/actions/setup-nodejs-context@v5.0.0
+      if: ${{ env.strategy == 'nodejs' }}
+      uses: giancosta86/aurora-github/actions/setup-nodejs-context@v6.0.0
       with:
-        registry-url: ${{ inputs.registry-url }}
-        frozen-lockfile: ${{ inputs.frozen-lockfile }}
         project-directory: ${{ inputs.root-directory }}
-        shell: ${{ inputs.shell }}
-
-    - name: Just install NodeJS dependencies
-      if: ${{ env.strategy == 'nodejs' && inputs.dedicated-env != 'true' }}
-      uses: giancosta86/aurora-github/actions/setup-nodejs-context@v5.0.0
-      with:
-        setup-nodejs: false
-        install-pnpm: false
-        registry-url: ${{ inputs.registry-url }}
-        frozen-lockfile: ${{ inputs.frozen-lockfile }}
-        project-directory: ${{ inputs.root-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Run the 'verify' script from package.json
       if: ${{ env.strategy == 'nodejs' }}
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.root-directory }}
       run: |
         echo "📦Now running the 'verify' script from package.json..."
         pnpm verify
 
+    - name: Check for the Rust toolchain file
+      if: ${{ env.strategy == 'rust' }}
+      shell: bash
+      working-directory: ${{ inputs.root-directory }}
+      run: |
+        if [[ -f "rust-toolchain.toml" ]]
+        then
+          echo "checkRustVersions=true" >> $GITHUB_ENV
+        else
+          echo "checkRustVersions=false" >> $GITHUB_ENV
+        fi
+
     - name: Check Rust versions
-      if: ${{ env.strategy == 'rust' && inputs.dedicated-env == 'true' }}
-      uses: giancosta86/aurora-github/actions/check-rust-versions@v5.0.0
+      if: ${{ env.strategy == 'rust' && env.checkRustVersions == 'true' }}
+      uses: giancosta86/aurora-github/actions/check-rust-versions@v6.0.0
       with:
         project-directory: ${{ inputs.root-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Run tests via Cargo
       if: ${{ env.strategy == 'rust' }}
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.root-directory }}
       run: |
         echo "🦀Running Rust tests with all the features enabled..."
@@ -144,5 +137,5 @@ runs:
 
     - name: Print confirmation message
       if: ${{ env.strategy != 'exit' }}
-      shell: ${{ inputs.shell }}
+      shell: bash
       run: echo "✅Custom tests in directory '${{ inputs.root-directory }}' run successfully!"
diff --git a/actions/verify-npm-package/action.yml b/actions/verify-npm-package/action.yml
--- a/actions/verify-npm-package/action.yml
+++ b/actions/verify-npm-package/action.yml
@@ -2,14 +2,6 @@ name: Verify npm package
 description: Verifies the source files of a NodeJS package - by running its 'verify' script within the 'scripts' section of 'package.json'.
 
 inputs:
-  registry-url:
-    description: The URL of the npm registry.
-    default: https://registry.npmjs.org
-
-  frozen-lockfile:
-    description: Fail if "pnpm-lock.yaml" is missing or outdated.
-    default: true
-
   crash-on-critical-todos:
     description: Crash the workflow if critical TODOs are found.
     default: true
@@ -30,37 +22,17 @@ inputs:
     description: Run check-subpath-exports after the "verify" package script.
     default: true
 
-  custom-test-env:
-    description: Create a dedicated environment for custom tests.
-    default: false
-
   project-directory:
     description: The directory containing package.json.
     default: .
-
-  shell:
-    description: The shell used to run commands.
-    default: bash
 
 runs:
   using: composite
   steps:
     - name: Validate inputs
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
-        if [[ -z "${{ inputs.registry-url }}" ]]
-        then
-          echo "❌Missing action input: 'registry-url'!" >&2
-          exit 1
-        fi
-
-        if [[ -z "${{ inputs.frozen-lockfile }}" ]]
-        then
-          echo "❌Missing action input: 'frozen-lockfile'!" >&2
-          exit 1
-        fi
-
         if [[ -z "${{ inputs.crash-on-critical-todos }}" ]]
         then
           echo "❌Missing action input: 'crash-on-critical-todos'!" >&2
@@ -85,6 +57,12 @@ runs:
           exit 1
         fi
 
+        if [[ -z "${{ inputs.check-subpath-exports }}" ]]
+        then
+          echo "❌Missing action input: 'check-subpath-exports'!" >&2
+          exit 1
+        fi
+
         if [[ ! -f "package.json" ]]
         then
           echo "❌The package.json descriptor file does not exist!!" >&2
@@ -93,14 +71,13 @@ runs:
 
     - name: Check artifact version
       if: ${{ inputs.check-artifact-version == 'true' }}
-      uses: giancosta86/aurora-github/actions/check-artifact-version@v5.0.0
+      uses: giancosta86/aurora-github/actions/check-artifact-version@v6.0.0
       with:
         project-directory: ${{ inputs.project-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Enforce ESM
       if: ${{ inputs.enforce-esm == 'true' }}
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
         packageType="$(jq -r .type package.json)"
@@ -117,47 +94,38 @@ runs:
         fi
 
     - name: Setup NodeJS context
-      uses: giancosta86/aurora-github/actions/setup-nodejs-context@v5.0.0
+      uses: giancosta86/aurora-github/actions/setup-nodejs-context@v6.0.0
       with:
-        registry-url: ${{ inputs.registry-url }}
-        frozen-lockfile: ${{ inputs.frozen-lockfile }}
         project-directory: ${{ inputs.project-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Run the 'verify' script from package.json
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
         echo "🔎Now running the 'verify' package.json script..."
         pnpm verify
         echo "✅'verify' script successful!"
 
-    - name: Run optional custom tests from the 'tests' directory
-      uses: giancosta86/aurora-github/actions/run-custom-tests@v5.0.0
-      with:
-        optional: true
-        dedicated-env: ${{ inputs.custom-test-env }}
-        registry-url: ${{ inputs.registry-url }}
-        frozen-lockfile: ${{ inputs.frozen-lockfile }}
-        root-directory: ${{ inputs.project-directory }}/tests
-        shell: ${{ inputs.shell }}
-
     - name: Check subpath exports
       if: ${{ inputs.check-subpath-exports == 'true' }}
-      uses: giancosta86/aurora-github/actions/check-subpath-exports@v5.0.0
+      uses: giancosta86/aurora-github/actions/check-subpath-exports@v6.0.0
       with:
         project-directory: ${{ inputs.project-directory }}
-        shell: ${{ inputs.shell }}
+
+    - name: Run optional custom tests from the 'tests' directory
+      uses: giancosta86/aurora-github/actions/run-custom-tests@v6.0.0
+      with:
+        optional: true
+        root-directory: ${{ inputs.project-directory }}/tests
 
     - name: Check for critical TODOs
-      uses: giancosta86/aurora-github/actions/find-critical-todos@v5.0.0
+      uses: giancosta86/aurora-github/actions/find-critical-todos@v6.0.0
       with:
         source-file-regex: ${{ inputs.source-file-regex }}
         crash-on-found: ${{ inputs.crash-on-critical-todos }}
         display-lines: true
         root-directory: ${{ inputs.project-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Print confirmation message
-      shell: ${{ inputs.shell }}
+      shell: bash
       run: echo "✅npm package source files verified!"
diff --git a/actions/verify-rust-wasm/action.yml b/actions/verify-rust-wasm/action.yml
--- a/actions/verify-rust-wasm/action.yml
+++ b/actions/verify-rust-wasm/action.yml
@@ -36,32 +36,26 @@ inputs:
     description: Ensure the version in Cargo.toml matches the branch name.
     default: true
 
-  registry-url:
-    description: The URL of the npm registry.
-    default: https://registry.npmjs.org
-
-  frozen-lockfile:
-    description: Fail if "pnpm-lock.yaml" is missing or outdated.
-    default: true
-
   project-directory:
     description: The directory containing Cargo.toml.
     default: .
-
-  shell:
-    description: The shell used to run commands
-    default: bash
 
 runs:
   using: composite
   steps:
     - name: Validate inputs
-      shell: ${{ inputs.shell }}
-      working-directory: ${{ inputs.root-directory }}
+      shell: bash
+      working-directory: ${{ inputs.project-directory }}
       run: |
         if [[ -z "${{ inputs.wasm-pack-version }}" ]]
         then
           echo "❌Missing action input: 'wasm-pack-version'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.npm-scope }}" ]]
+        then
+          echo "❌Missing action input: 'npm-scope'!" >&2
           exit 1
         fi
 
@@ -107,32 +101,19 @@ runs:
           exit 1
         fi
 
-        if [[ -z "${{ inputs.registry-url }}" ]]
-        then
-          echo "❌Missing action input: 'registry-url'!" >&2
-          exit 1
-        fi
-
-        if [[ -z "${{ inputs.frozen-lockfile }}" ]]
-        then
-          echo "❌Missing action input: 'frozen-lockfile'!" >&2
-          exit 1
-        fi
-
     - name: Parse npm scope
       id: parse-npm-scope
-      uses: giancosta86/aurora-github/actions/parse-npm-scope@v5.0.0
+      uses: giancosta86/aurora-github/actions/parse-npm-scope@v6.0.0
       with:
         scope: ${{ inputs.npm-scope }}
 
     - name: Install wasm-pack
-      uses: giancosta86/aurora-github/actions/install-wasm-pack@v5.0.0
+      uses: giancosta86/aurora-github/actions/install-wasm-pack@v6.0.0
       with:
         wasm-pack-version: ${{ inputs.wasm-pack-version }}
-        shell: ${{ inputs.shell }}
 
     - name: Verify Rust source files
-      uses: giancosta86/aurora-github/actions/verify-rust-crate@v5.0.0
+      uses: giancosta86/aurora-github/actions/verify-rust-crate@v6.0.0
       with:
         run-clippy-checks: ${{ inputs.run-clippy-checks }}
         check-rustdoc: ${{ inputs.check-rustdoc }}
@@ -140,10 +121,9 @@ runs:
         source-file-regex: ${{ inputs.source-file-regex }}
         check-artifact-version: ${{ inputs.check-artifact-version }}
         project-directory: ${{ inputs.project-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Run headless browser tests
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
         echo "🌐Running headless browser tests..."
@@ -151,7 +131,7 @@ runs:
         echo "✅Headless browser tests OK!"
 
     - name: Generate the NodeJS package source files
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
         scope="${{ steps.parse-npm-scope.outputs.actual-scope }}"
@@ -164,15 +144,11 @@ runs:
         fi
 
     - name: Run client tests
-      uses: giancosta86/aurora-github/actions/run-custom-tests@v5.0.0
+      uses: giancosta86/aurora-github/actions/run-custom-tests@v6.0.0
       with:
         optional: true
-        dedicated-env: true
-        registry-url: ${{ inputs.registry-url }}
-        frozen-lockfile: ${{ inputs.frozen-lockfile }}
         root-directory: ${{ inputs.project-directory }}/${{ inputs.client-tests-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Print confirmation message
-      shell: ${{ inputs.shell }}
+      shell: bash
       run: echo "✅Rust web assembly source files verified!"
