Add the `registry-url` input to all the npm-related actions

diff --git a/actions/publish-npm-package/action.yml b/actions/publish-npm-package/action.yml
--- a/actions/publish-npm-package/action.yml
+++ b/actions/publish-npm-package/action.yml
@@ -1,5 +1,5 @@
 name: Publish npm package
-description: Publishes a NodeJS package to the npm registry.
+description: Publishes a NodeJS package to an npm registry.
 
 inputs:
   dry-run:
@@ -7,7 +7,11 @@ inputs:
     default: false
 
   npm-token:
-    description: The secret token for publishing to npm.
+    description: The secret token for publishing to the registry.
+
+  registry-url:
+    description: The URL of the npm registry.
+    default: https://registry.npmjs.org
 
   frozen-lockfile:
     description: Fail if 'pnpm-lock.yaml' is missing or outdated.
@@ -40,6 +44,12 @@ runs:
           exit 1
         fi
 
+        if [[ -z "${{ inputs.registry-url }}" ]]
+        then
+          echo "❌Missing action input: 'registry-url'!" >&2
+          exit 1
+        fi
+
         if [[ -z "${{ inputs.frozen-lockfile }}" ]]
         then
           echo "❌Missing action input: 'frozen-lockfile'!" >&2
@@ -52,30 +62,6 @@ runs:
           exit 1
         fi
 
-    - name: Setup NodeJS and NPM registry
-      uses: actions/setup-node@v4
-      with:
-        node-version-file: ${{ inputs.project-directory }}/.nvmrc
-        registry-url: https://registry.npmjs.org
-
-    - name: Install pnpm
-      uses: pnpm/action-setup@v4
-      with:
-        version: 9
-
-    - name: Install dependencies
-      shell: ${{ inputs.shell }}
-      working-directory: ${{ inputs.project-directory }}
-      run: |
-        frozenLockfile="${{ inputs.frozen-lockfile }}"
-
-        if [[ "$frozenLockfile" == "true" ]]
-        then
-          pnpm install --frozen-lockfile
-        else
-          pnpm install --no-frozen-lockfile
-        fi
-
     - name: Display the artifact descriptor
       shell: ${{ inputs.shell }}
       working-directory: ${{ inputs.project-directory }}
@@ -83,13 +69,19 @@ runs:
         echo "The content of your 📦package.json just before publication is:"
         jq . package.json
 
+    - name: Setup NodeJS context
+      uses: giancosta86/aurora-github/actions/setup-nodejs-context@v4.0.0
+      with:
+        registry-url: ${{ inputs.registry-url }}
+        frozen-lockfile: ${{ inputs.frozen-lockfile }}
+        project-directory: ${{ inputs.project-directory }}
+        shell: ${{ inputs.shell }}
+
     - name: Publish to npm
       shell: ${{ inputs.shell }}
       working-directory: ${{ inputs.project-directory }}
       run: |
-        dryRun="${{ inputs.dry-run }}"
-
-        if [[ "$dryRun" == "true" ]]
+        if [[ "${{ inputs.dry-run }}" == "true" ]]
         then
           pnpm publish --no-git-checks --access public --dry-run
         else
