Introduce v4.0.0 (#13)
* Introduce the `inject-subpath-exports` action (closes #12)

* Introduce the `check-subpath-exports` action

* Introduce the `publish-github-pages` action

* Introduce the `setup-nodejs-context` action

* Introduce the `install-system-packages` action

* Simplify `find-critical-todos` and its documentation

* Add the `registry-url` input to all the npm-related actions

* Add the `enforce-esm` input to `verify-npm-package`

* Check that package.json exists as a prerequisite for npm actions

* Improve the tests and the related projects

* Simplify all the `find` calls

* Fix whitespace and formatting

* Improve the output messages

* Use `jq` instead of `cat` to print out `package.json`

* Extend the documentation

* Explain the permission required by `tag-and-release`

* Add standard emojis to the READMEs

* Remove the misleading `required` attribute from action inputs

* Update repository description

* Update the action diagram

diff --git a/actions/publish-npm-package/action.yml b/actions/publish-npm-package/action.yml
--- a/actions/publish-npm-package/action.yml
+++ b/actions/publish-npm-package/action.yml
@@ -1,29 +1,28 @@
 name: Publish npm package
-description: Publishes a NodeJS package to the npm registry.
+description: Publishes a NodeJS package to an npm registry.
 
 inputs:
   dry-run:
     description: Run a simulated publication via --dry-run.
-    required: false
     default: false
-    
+
   npm-token:
-    description: The secret token for publishing to npm.
-    required: true  
+    description: The secret token for publishing to the registry.
+
+  registry-url:
+    description: The URL of the npm registry.
+    default: https://registry.npmjs.org
 
   frozen-lockfile:
     description: Fail if 'pnpm-lock.yaml' is missing or outdated.
-    required: false
     default: true
 
   project-directory:
     description: The directory containing package.json.
-    required: false
     default: .
 
   shell:
     description: The shell used to run commands.
-    required: false
     default: bash
 
 runs:
@@ -31,6 +30,7 @@ runs:
   steps:
     - name: Validate inputs
       shell: ${{ inputs.shell }}
+      working-directory: ${{ inputs.project-directory }}
       run: |
         if [[ -z "${{ inputs.dry-run }}" ]]
         then
@@ -44,34 +44,22 @@ runs:
           exit 1
         fi
 
+        if [[ -z "${{ inputs.registry-url }}" ]]
+        then
+          echo "❌Missing action input: 'registry-url'!" >&2
+          exit 1
+        fi
+
         if [[ -z "${{ inputs.frozen-lockfile }}" ]]
         then
           echo "❌Missing action input: 'frozen-lockfile'!" >&2
           exit 1
         fi
 
-    - name: Setup NodeJS and NPM registry
-      uses: actions/setup-node@v4
-      with:
-        node-version-file: ${{ inputs.project-directory }}/.nvmrc
-        registry-url: https://registry.npmjs.org
-
-    - name: Install pnpm
-      uses: pnpm/action-setup@v4
-      with:
-        version: 9
-
-    - name: Install dependencies
-      shell: ${{ inputs.shell }}
-      working-directory: ${{ inputs.project-directory }}
-      run: |
-        frozenLockfile="${{ inputs.frozen-lockfile }}"
-
-        if [[ "$frozenLockfile" == "true" ]]
+        if [[ ! -f "package.json" ]]
         then
-          pnpm install --frozen-lockfile
-        else
-          pnpm install --no-frozen-lockfile
+          echo "❌The package.json descriptor file does not exist!!" >&2
+          exit 1
         fi
 
     - name: Display the artifact descriptor
@@ -79,15 +67,21 @@ runs:
       working-directory: ${{ inputs.project-directory }}
       run: |
         echo "The content of your 📦package.json just before publication is:"
-        cat package.json
+        jq . package.json
+
+    - name: Setup NodeJS context
+      uses: giancosta86/aurora-github/actions/setup-nodejs-context@v4.0.0
+      with:
+        registry-url: ${{ inputs.registry-url }}
+        frozen-lockfile: ${{ inputs.frozen-lockfile }}
+        project-directory: ${{ inputs.project-directory }}
+        shell: ${{ inputs.shell }}
 
     - name: Publish to npm
       shell: ${{ inputs.shell }}
       working-directory: ${{ inputs.project-directory }}
       run: |
-        dryRun="${{ inputs.dry-run }}"
-
-        if [[ "$dryRun" == "true" ]]
+        if [[ "${{ inputs.dry-run }}" == "true" ]]
         then
           pnpm publish --no-git-checks --access public --dry-run
         else
@@ -95,3 +89,8 @@ runs:
         fi
       env:
         NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
+
+    - name: Print confirmation message
+      shell: ${{ inputs.shell }}
+      run: |
+        echo "✅Publication to '${{ inputs.registry-url }}' successful!"
diff --git a/actions/tag-and-release/action.yml b/actions/tag-and-release/action.yml
--- a/actions/tag-and-release/action.yml
+++ b/actions/tag-and-release/action.yml
@@ -4,27 +4,34 @@ description: Creates a Git tag and a GitHub release, from a Git branch named acc
 inputs:
   draft-only:
     description: Only draft the release.
-    required: false
     default: false
 
   delete-branch:
     description: Delete the branch after creating the tag.
-    required: false
     default: true
 
   set-major-tag:
     description: Create/move the 'vX' tag to this commit (X=major version)
-    required: false
     default: false
 
   shell:
     description: The shell used to run commands.
-    required: false
     default: bash
 
 runs:
   using: composite
   steps:
+    - name: Ensure the action is invoked when merging a pull request
+      shell: ${{ inputs.shell }}
+      run: |
+        inPullRequestMerging="$(jq -r .pull_request.merged "$GITHUB_EVENT_PATH")"
+
+        if [[ "$inPullRequestMerging" != "true" ]]
+        then
+          echo "❌This action can only be invoked when merging a pull request!" >&2
+          exit 1
+        fi
+
     - name: Validate inputs
       shell: ${{ inputs.shell }}
       run: |
@@ -48,7 +55,7 @@ runs:
 
     - name: Detect branch and version
       id: detect-branch-version
-      uses: giancosta86/aurora-github/actions/detect-branch-version@v3.0.0
+      uses: giancosta86/aurora-github/actions/detect-branch-version@v4.0.0
       with:
         shell: ${{ inputs.shell }}
 
@@ -56,22 +63,24 @@ runs:
       shell: ${{ inputs.shell }}
       run: |
         branch="${{ steps.detect-branch-version.outputs.branch }}"
+        defaultBranch="${{ github.event.repository.default_branch }}"
         version="${{ steps.detect-branch-version.outputs.version }}"
         major="${{ steps.detect-branch-version.outputs.major }}"
-        defaultBranch="${{ github.event.repository.default_branch }}"
         setMajorTag=${{ inputs.set-major-tag == 'true' }}
 
-        echo "🌲It seems your default branch is: '$defaultBranch'"
-
-        if [[ -z "$branch" ]]
+        if [[ -n "$branch" ]]
         then
+          echo "🌲Current branch: '$branch'"
+        else
           echo "❌The current Git branch could not be detected!" >&2
           exit 1
         fi
 
+        echo "🌲Default repository branch: '$defaultBranch'"
+
         if [[ "$branch" == "$defaultBranch" ]]
         then
-          echo "❌This action cannot be run from the default branch ('$defaultBranch')!" >&2
+          echo "❌This action cannot be run from the default branch!" >&2
           exit 1
         fi
 
@@ -83,7 +92,7 @@ runs:
 
         if [[ "$setMajorTag" == "true" && -z "$major" ]]
         then
-          echo "❌The major version could not be detected from the Git branch or the version!" >&2
+          echo "❌The major version could not be detected!" >&2
           exit 1
         fi
 
@@ -118,20 +127,19 @@ runs:
       run: |
         draftOnly="${{ inputs.draft-only }}"
         version="${{ steps.detect-branch-version.outputs.version }}"
-        tag="${{ steps.create-git-tag.outputs.tag }}" 
+        tag="${{ steps.create-git-tag.outputs.tag }}"
 
         repoBasename="$(basename "$GITHUB_REPOSITORY")"
-        releaseTitle="$repoBasename $version"        
-
-        releaseRecap="release '$releaseTitle' from tag '$tag'"
+        releaseTitle="$repoBasename $version"
+        releaseRecapMessage="release '$releaseTitle' from tag '$tag'"
 
         if [[ "$draftOnly" = true ]]
         then
-          echo "📝Drafting $releaseRecap..."
+          echo "📝Drafting $releaseRecapMessage..."
           gh release create "$tag" --title "$releaseTitle" --draft
           echo "📝Release drafted!"
-        else 
-          echo "🌟Creating $releaseRecap..."
+        else
+          echo "🌟Creating $releaseRecapMessage..."
           gh release create "$tag" --title "$releaseTitle"
           echo "🌟Release created!"
         fi
