Redesign `publish-rust-wasm`:
* Drop the **node-version-directory** input

* Add new inputs, passed to `generate-wasm-target`:

  * **nodejs-version**

  * **pnpm-version**

* Do not use `.nvmrc` and `.pnpmrc` files any more

* If a `.npmrc` configuration file exists in `project-directory`, copy it to **pkg** just before publishing

diff --git a/actions/publish-rust-wasm/action.yml b/actions/publish-rust-wasm/action.yml
--- a/actions/publish-rust-wasm/action.yml
+++ b/actions/publish-rust-wasm/action.yml
@@ -15,13 +15,15 @@ inputs:
   npm-scope:
     description: The npm package scope or "<ROOT>".
 
+  nodejs-version:
+    description: The "engines / node" version within package.json.
+
+  pnpm-version:
+    description: The "packageManager" reference to pnpm within package.json.
+
   wasm-target:
     description: The target of the 'wasm-pack build' command.
     default: web
-
-  node-version-directory:
-    description: Relative directory containing the .nvmrc file.
-    default: client-tests
 
   website-directory:
     description: Relative directory containing the project website.
@@ -66,15 +68,15 @@ runs:
           exit 1
         fi
 
-        if [[ -z "${{ inputs.wasm-target }}" ]]
+        if [[ -z "${{ inputs.nodejs-version }}" ]]
         then
-          echo "❌Missing action input: 'wasm-target'!" >&2
+          echo "❌Missing action input: 'nodejs-version'!" >&2
           exit 1
         fi
 
-        if [[ -z "${{ inputs.node-version-directory }}" ]]
+        if [[ -z "${{ inputs.wasm-target }}" ]]
         then
-          echo "❌Missing action input: 'node-version-directory'!" >&2
+          echo "❌Missing action input: 'wasm-target'!" >&2
           exit 1
         fi
 
@@ -100,14 +102,26 @@ runs:
       with:
         target: ${{ inputs.wasm-target }}
         npm-scope: ${{ inputs.npm-scope }}
+        nodejs-version: ${{ inputs.nodejs-version }}
+        pnpm-version: ${{ inputs.pnpm-version }}
         development: false
         target-directory: pkg
         project-directory: ${{ inputs.project-directory }}
 
-    - name: Copy .nvmrc to the generated NodeJS package
+    - name: Try to copy .npmrc from the project directory
       shell: bash
       working-directory: ${{ inputs.project-directory }}
-      run: cp "${{ inputs.node-version-directory }}/.nvmrc" pkg
+      run: |
+        if [[ -f ".npmrc" ]]
+        then
+          echo "🎉.npmrc configuration file found! Copying it to the package directory..."
+
+          cp .npmrc pkg/
+
+          echo "✅.npmrc file copied!"
+        else
+          echo "💭No .npmrc configuration file found in the project directory..."
+        fi
 
     - name: Publish NodeJS package
       uses: giancosta86/aurora-github/actions/publish-npm-package@v8.0.0
