Enforce stricter input checks for several actions

diff --git a/actions/publish-rust-crate/action.yml b/actions/publish-rust-crate/action.yml
--- a/actions/publish-rust-crate/action.yml
+++ b/actions/publish-rust-crate/action.yml
@@ -50,6 +50,18 @@ runs:
           exit 1
         fi
 
+        if [[ -z "${{ inputs.website-directory }}" ]]
+        then
+          echo "❌Missing action input: 'website-directory'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.enforce-branch-version }}" ]]
+        then
+          echo "❌Missing action input: 'enforce-branch-version'!" >&2
+          exit 1
+        fi
+
     - name: Enforce branch version
       uses: giancosta86/aurora-github/actions/enforce-branch-version@v7.0.0
       with:
diff --git a/actions/publish-rust-wasm/action.yml b/actions/publish-rust-wasm/action.yml
--- a/actions/publish-rust-wasm/action.yml
+++ b/actions/publish-rust-wasm/action.yml
@@ -78,6 +78,18 @@ runs:
           exit 1
         fi
 
+        if [[ -z "${{ inputs.website-directory }}" ]]
+        then
+          echo "❌Missing action input: 'website-directory'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.enforce-branch-version }}" ]]
+        then
+          echo "❌Missing action input: 'enforce-branch-version'!" >&2
+          exit 1
+        fi
+
     - name: Parse npm scope
       id: parse-npm-scope
       uses: giancosta86/aurora-github/actions/parse-npm-scope@v7.0.0
diff --git a/actions/verify-rust-crate/action.yml b/actions/verify-rust-crate/action.yml
--- a/actions/verify-rust-crate/action.yml
+++ b/actions/verify-rust-crate/action.yml
@@ -57,6 +57,12 @@ runs:
           exit 1
         fi
 
+        if [[ -z "${{ inputs.enforce-branch-version }}" ]]
+        then
+          echo "❌Missing action input: 'enforce-branch-version'!" >&2
+          exit 1
+        fi
+
     - name: Enforce branch version
       uses: giancosta86/aurora-github/actions/enforce-branch-version@v7.0.0
       with:
