Remove every `shell` input

diff --git a/actions/run-custom-tests/action.yml b/actions/run-custom-tests/action.yml
--- a/actions/run-custom-tests/action.yml
+++ b/actions/run-custom-tests/action.yml
@@ -17,16 +17,18 @@ inputs:
   root-directory:
     description: The directory containing the tests.
 
-  shell:
-    description: The shell used to run commands.
-    default: bash
-
 runs:
   using: composite
   steps:
     - name: Detect directory existence
-      shell: ${{ inputs.shell }}
+      shell: bash
       run: |
+        if [[ -z "${{ inputs.optional }}" ]]
+        then
+          echo "❌Missing action input: 'optional'!" >&2
+          exit 1
+        fi
+
         if [[ ! -d "${{ inputs.root-directory }}" ]]
         then
           if [[ "${{ inputs.optional }}" == "true" ]]
@@ -44,7 +46,7 @@ runs:
 
     - name: Validate inputs
       if: ${{ env.strategy == 'detect' }}
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.root-directory }}
       run: |
         echo "🔬Detecting custom test strategy in directory '${{ inputs.root-directory }}'..."
@@ -55,6 +57,12 @@ runs:
         then
           echo "🐚Custom test script '$scriptFile' found!"
           strategy="script"
+
+          if [[ -z "${{ inputs.script-shell }}" ]]
+          then
+            echo "❌Missing action input: 'script-shell'!" >&2
+            exit 1
+          fi
         elif [[ -f "package.json" ]]
         then
           echo "📦package.json file found!"
@@ -80,7 +88,7 @@ runs:
 
     - name: Run script
       if: ${{ env.strategy == 'script' }}
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.root-directory }}
       run: |
         echo "🐚Now running the custom script '${{ inputs.script-file }}'..."
@@ -92,19 +100,18 @@ runs:
       uses: giancosta86/aurora-github/actions/setup-nodejs-context@v6.0.0
       with:
         project-directory: ${{ inputs.root-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Run the 'verify' script from package.json
       if: ${{ env.strategy == 'nodejs' }}
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.root-directory }}
       run: |
         echo "📦Now running the 'verify' script from package.json..."
         pnpm verify
 
-    - name: Check Rust versions
+    - name: Check for the Rust toolchain file
       if: ${{ env.strategy == 'rust' }}
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.root-directory }}
       run: |
         if [[ -f "rust-toolchain.toml" ]]
@@ -119,11 +126,10 @@ runs:
       uses: giancosta86/aurora-github/actions/check-rust-versions@v6.0.0
       with:
         project-directory: ${{ inputs.root-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Run tests via Cargo
       if: ${{ env.strategy == 'rust' }}
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.root-directory }}
       run: |
         echo "🦀Running Rust tests with all the features enabled..."
@@ -131,5 +137,5 @@ runs:
 
     - name: Print confirmation message
       if: ${{ env.strategy != 'exit' }}
-      shell: ${{ inputs.shell }}
+      shell: bash
       run: echo "✅Custom tests in directory '${{ inputs.root-directory }}' run successfully!"
diff --git a/actions/verify-npm-package/action.yml b/actions/verify-npm-package/action.yml
--- a/actions/verify-npm-package/action.yml
+++ b/actions/verify-npm-package/action.yml
@@ -26,15 +26,11 @@ inputs:
     description: The directory containing package.json.
     default: .
 
-  shell:
-    description: The shell used to run commands.
-    default: bash
-
 runs:
   using: composite
   steps:
     - name: Validate inputs
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
         if [[ -z "${{ inputs.crash-on-critical-todos }}" ]]
@@ -61,6 +57,12 @@ runs:
           exit 1
         fi
 
+        if [[ -z "${{ inputs.check-subpath-exports }}" ]]
+        then
+          echo "❌Missing action input: 'check-subpath-exports'!" >&2
+          exit 1
+        fi
+
         if [[ ! -f "package.json" ]]
         then
           echo "❌The package.json descriptor file does not exist!!" >&2
@@ -72,11 +74,10 @@ runs:
       uses: giancosta86/aurora-github/actions/check-artifact-version@v6.0.0
       with:
         project-directory: ${{ inputs.project-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Enforce ESM
       if: ${{ inputs.enforce-esm == 'true' }}
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
         packageType="$(jq -r .type package.json)"
@@ -96,10 +97,9 @@ runs:
       uses: giancosta86/aurora-github/actions/setup-nodejs-context@v6.0.0
       with:
         project-directory: ${{ inputs.project-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Run the 'verify' script from package.json
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
         echo "🔎Now running the 'verify' package.json script..."
@@ -111,14 +111,12 @@ runs:
       uses: giancosta86/aurora-github/actions/check-subpath-exports@v6.0.0
       with:
         project-directory: ${{ inputs.project-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Run optional custom tests from the 'tests' directory
       uses: giancosta86/aurora-github/actions/run-custom-tests@v6.0.0
       with:
         optional: true
         root-directory: ${{ inputs.project-directory }}/tests
-        shell: ${{ inputs.shell }}
 
     - name: Check for critical TODOs
       uses: giancosta86/aurora-github/actions/find-critical-todos@v6.0.0
@@ -127,8 +125,7 @@ runs:
         crash-on-found: ${{ inputs.crash-on-critical-todos }}
         display-lines: true
         root-directory: ${{ inputs.project-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Print confirmation message
-      shell: ${{ inputs.shell }}
+      shell: bash
       run: echo "✅npm package source files verified!"
diff --git a/actions/verify-rust-wasm/action.yml b/actions/verify-rust-wasm/action.yml
--- a/actions/verify-rust-wasm/action.yml
+++ b/actions/verify-rust-wasm/action.yml
@@ -40,20 +40,22 @@ inputs:
     description: The directory containing Cargo.toml.
     default: .
 
-  shell:
-    description: The shell used to run commands
-    default: bash
-
 runs:
   using: composite
   steps:
     - name: Validate inputs
-      shell: ${{ inputs.shell }}
-      working-directory: ${{ inputs.root-directory }}
+      shell: bash
+      working-directory: ${{ inputs.project-directory }}
       run: |
         if [[ -z "${{ inputs.wasm-pack-version }}" ]]
         then
           echo "❌Missing action input: 'wasm-pack-version'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.npm-scope }}" ]]
+        then
+          echo "❌Missing action input: 'npm-scope'!" >&2
           exit 1
         fi
 
@@ -109,7 +111,6 @@ runs:
       uses: giancosta86/aurora-github/actions/install-wasm-pack@v6.0.0
       with:
         wasm-pack-version: ${{ inputs.wasm-pack-version }}
-        shell: ${{ inputs.shell }}
 
     - name: Verify Rust source files
       uses: giancosta86/aurora-github/actions/verify-rust-crate@v6.0.0
@@ -120,10 +121,9 @@ runs:
         source-file-regex: ${{ inputs.source-file-regex }}
         check-artifact-version: ${{ inputs.check-artifact-version }}
         project-directory: ${{ inputs.project-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Run headless browser tests
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
         echo "🌐Running headless browser tests..."
@@ -131,7 +131,7 @@ runs:
         echo "✅Headless browser tests OK!"
 
     - name: Generate the NodeJS package source files
-      shell: ${{ inputs.shell }}
+      shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
         scope="${{ steps.parse-npm-scope.outputs.actual-scope }}"
@@ -148,8 +148,7 @@ runs:
       with:
         optional: true
         root-directory: ${{ inputs.project-directory }}/${{ inputs.client-tests-directory }}
-        shell: ${{ inputs.shell }}
 
     - name: Print confirmation message
-      shell: ${{ inputs.shell }}
+      shell: bash
       run: echo "✅Rust web assembly source files verified!"
