Improve input checks and documentation for several actions

diff --git a/actions/find-critical-todos/action.yml b/actions/find-critical-todos/action.yml
--- a/actions/find-critical-todos/action.yml
+++ b/actions/find-critical-todos/action.yml
@@ -33,7 +33,7 @@ outputs:
 runs:
   using: composite
   steps:
-    - name: Validate parameters
+    - name: Validate inputs
       shell: ${{ inputs.shell }}
       working-directory: ${{ inputs.root-directory }}
       run: |
@@ -46,6 +46,12 @@ runs:
         if [[ -z "${{ inputs.crash-on-found }}" ]]
         then
           echo "❌Missing action input: 'crash-on-found'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.display-lines }}" ]]
+        then
+          echo "❌Missing action input: 'display-lines'!" >&2
           exit 1
         fi
 
diff --git a/actions/publish-rust-crate/action.yml b/actions/publish-rust-crate/action.yml
--- a/actions/publish-rust-crate/action.yml
+++ b/actions/publish-rust-crate/action.yml
@@ -2,14 +2,14 @@ name: Publish to crates.io
 description: Publishes a Rust crate to crates.io, with all of its features enabled.
 
 inputs:
-  cargo-token:
-    description: The secret token for publishing to crates.io.
-    required: true
-
   dry-run:
     description: Run a simulated publication via --dry-run.
     required: false
     default: false
+
+  cargo-token:
+    description: The secret token for publishing to crates.io.
+    required: true
 
   document-all-features:
     description: Enable Rustdoc for all features.
@@ -29,6 +29,27 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: ${{ inputs.shell }}
+      run: |
+        if [[ -z "${{ inputs.dry-run }}" ]]
+        then
+          echo "❌Missing action input: 'dry-run'!" >&2
+          exit 1
+        fi
+        
+        if [[ ${{ inputs.dry-run }} != 'true' && -z "${{ inputs.cargo-token }}" ]]
+        then
+          echo "❌Missing action input: 'cargo-token'!" >&2
+          exit 1
+        fi        
+
+        if [[ -z "${{ inputs.document-all-features }}" ]]
+        then
+          echo "❌Missing action input: 'document-all-features'!" >&2
+          exit 1
+        fi
+
     - name: Enable Rustdoc for all features
       if: ${{ inputs.document-all-features == 'true' }}
       shell: ${{ inputs.shell }}
diff --git a/actions/publish-rust-wasm/action.yml b/actions/publish-rust-wasm/action.yml
--- a/actions/publish-rust-wasm/action.yml
+++ b/actions/publish-rust-wasm/action.yml
@@ -42,6 +42,39 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: ${{ inputs.shell }}
+      run: |
+        if [[ ${{ inputs.dry-run }} != 'true' && -z "${{ inputs.npm-token }}" ]]
+        then
+          echo "❌Missing action input: 'npm-token'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.wasm-pack-version }}" ]]
+        then
+          echo "❌Missing action input: 'wasm-pack-version'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.dry-run }}" ]]
+        then
+          echo "❌Missing action input: 'dry-run'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.wasm-target }}" ]]
+        then
+          echo "❌Missing action input: 'wasm-target'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.node-version-directory }}" ]]
+        then
+          echo "❌Missing action input: 'node-version-directory'!" >&2
+          exit 1
+        fi
+
     - name: Install wasm-pack
       uses: giancosta86/aurora-github/actions/install-wasm-pack@v3.0.0
       with:
diff --git a/actions/tag-and-release/action.yml b/actions/tag-and-release/action.yml
--- a/actions/tag-and-release/action.yml
+++ b/actions/tag-and-release/action.yml
@@ -25,6 +25,27 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: ${{ inputs.shell }}
+      run: |
+        if [[ -z "${{ inputs.draft-only }}" ]]
+        then
+          echo "❌Missing action input: 'draft-only'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.delete-branch }}" ]]
+        then
+          echo "❌Missing action input: 'delete-branch'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.set-major-tag }}" ]]
+        then
+          echo "❌Missing action input: 'set-major-tag'!" >&2
+          exit 1
+        fi
+
     - name: Detect branch and version
       id: detect-branch-version
       uses: giancosta86/aurora-github/actions/detect-branch-version@v3.0.0
diff --git a/actions/verify-npm-package/action.yml b/actions/verify-npm-package/action.yml
--- a/actions/verify-npm-package/action.yml
+++ b/actions/verify-npm-package/action.yml
@@ -15,7 +15,7 @@ inputs:
   source-file-regex:
     description: PCRE pattern describing the source files.
     required: false
-    default: '\.(j|t)sx?$'
+    default: '\.(c|m)?(j|t)sx?$'
 
   check-artifact-version:
     description: Ensure the version in package.json matches the branch name.
@@ -35,6 +35,41 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: ${{ inputs.shell }}
+      working-directory: ${{ inputs.root-directory }}
+      run: |
+        if [[ -z "${{ inputs.frozen-lockfile }}" ]]
+        then
+          echo "❌Missing action input: 'frozen-lockfile'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.crash-on-critical-todos }}" ]]
+        then
+          echo "❌Missing action input: 'crash-on-critical-todos'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.source-file-regex }}" ]]
+        then
+          echo "❌Missing action input: 'source-file-regex'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.check-artifact-version }}" ]]
+        then
+          echo "❌Missing action input: 'check-artifact-version'!" >&2
+          exit 1
+        fi
+    
+    - name: Check artifact version
+      if: ${{ inputs.check-artifact-version == 'true' }}
+      uses: giancosta86/aurora-github/actions/check-artifact-version@v3.0.0
+      with:
+        project-directory: ${{ inputs.project-directory }}
+        shell: ${{ inputs.shell }}
+
     - name: Check for critical TODOs
       uses: giancosta86/aurora-github/actions/find-critical-todos@v3.0.0
       with:
@@ -42,13 +77,6 @@ runs:
         crash-on-found: ${{ inputs.crash-on-critical-todos }}
         display-lines: true
         root-directory: ${{ inputs.project-directory }}
-        shell: ${{ inputs.shell }}
-
-    - name: Check artifact version
-      if: ${{ inputs.check-artifact-version == 'true' }}
-      uses: giancosta86/aurora-github/actions/check-artifact-version@v3.0.0
-      with:
-        project-directory: ${{ inputs.project-directory }}
         shell: ${{ inputs.shell }}
 
     - name: Setup NodeJS
diff --git a/actions/verify-rust-crate/action.yml b/actions/verify-rust-crate/action.yml
--- a/actions/verify-rust-crate/action.yml
+++ b/actions/verify-rust-crate/action.yml
@@ -40,6 +40,40 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: ${{ inputs.shell }}
+      working-directory: ${{ inputs.root-directory }}
+      run: |
+        if [[ -z "${{ inputs.run-clippy-checks }}" ]]
+        then
+          echo "❌Missing action input: 'run-clippy-checks'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.run-doc-checks }}" ]]
+        then
+          echo "❌Missing action input: 'run-doc-checks'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.crash-on-critical-todos }}" ]]
+        then
+          echo "❌Missing action input: 'crash-on-critical-todos'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.source-file-regex }}" ]]
+        then
+          echo "❌Missing action input: 'source-file-regex'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.check-artifact-version }}" ]]
+        then
+          echo "❌Missing action input: 'check-artifact-version'!" >&2
+          exit 1
+        fi
+
     - name: Check artifact version
       if: ${{ inputs.check-artifact-version == 'true' }}
       uses: giancosta86/aurora-github/actions/check-artifact-version@v3.0.0
diff --git a/actions/verify-rust-wasm/action.yml b/actions/verify-rust-wasm/action.yml
--- a/actions/verify-rust-wasm/action.yml
+++ b/actions/verify-rust-wasm/action.yml
@@ -30,6 +30,16 @@ inputs:
     required: false
     default: false
 
+  crash-on-critical-todos:
+    description: Crash the workflow if critical TODOs are found.
+    required: false
+    default: true
+
+  source-file-regex:
+    description: PCRE pattern describing the source files.
+    required: false
+    default: '\.rs$'
+
   check-artifact-version:
     description: Ensure the version in Cargo.toml matches the branch name.
     required: false
@@ -48,6 +58,52 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: ${{ inputs.shell }}
+      working-directory: ${{ inputs.root-directory }}
+      run: |
+        if [[ -z "${{ inputs.wasm-pack-version }}" ]]
+        then
+          echo "❌Missing action input: 'wasm-pack-version'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.wasm-target }}" ]]
+        then
+          echo "❌Missing action input: 'wasm-target'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.run-clippy-checks }}" ]]
+        then
+          echo "❌Missing action input: 'run-clippy-checks'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.run-doc-checks }}" ]]
+        then
+          echo "❌Missing action input: 'run-doc-checks'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.crash-on-critical-todos }}" ]]
+        then
+          echo "❌Missing action input: 'crash-on-critical-todos'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.source-file-regex }}" ]]
+        then
+          echo "❌Missing action input: 'source-file-regex'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.check-artifact-version }}" ]]
+        then
+          echo "❌Missing action input: 'check-artifact-version'!" >&2
+          exit 1
+        fi
+
     - name: Install wasm-pack
       uses: giancosta86/aurora-github/actions/install-wasm-pack@v3.0.0
       with:
@@ -59,6 +115,8 @@ runs:
       with:
         run-clippy-checks: ${{ inputs.run-clippy-checks }}
         run-doc-checks: ${{ inputs.run-doc-checks }}
+        crash-on-critical-todos: ${{ inputs.crash-on-critical-todos }}
+        source-file-regex: ${{ inputs.source-file-regex }}
         check-artifact-version: ${{ inputs.check-artifact-version }}
         project-directory: ${{ inputs.project-directory }}
         shell: ${{ inputs.shell }}
