Refactor Bash flow for actions:
* `check-rust-versions`

* `install-via-sdkman`

* `install-wasm-pack`

* `upload-release-assets`

* `check-subpath-exports`

* `inject-subpath-exports`

* `install-system-packages`

* `find-critical-todos`

* `publish-rust-crate`

* `run-custom-tests`

diff --git a/actions/find-critical-todos/action.yml b/actions/find-critical-todos/action.yml
--- a/actions/find-critical-todos/action.yml
+++ b/actions/find-critical-todos/action.yml
@@ -24,82 +24,96 @@ inputs:
 outputs:
   found:
     description: true if at least one TODO! was found in some file, false otherwise.
-    value: ${{ steps.scan-directory-tree.outputs.found }}
+    value: ${{ steps.main.outputs.found }}
 
 runs:
   using: composite
   steps:
-    - name: Validate inputs
+    - id: main
       shell: bash
       working-directory: ${{ inputs.root-directory }}
       run: |
-        if [[ -z "${{ inputs.source-file-regex }}" ]]
-        then
-          echo "❌Missing action input: 'source-file-regex'!" >&2
-          exit 1
-        fi
+        todoText="TODO!"
 
-        if [[ -z "${{ inputs.crash-on-found }}" ]]
-        then
-          echo "❌Missing action input: 'crash-on-found'!" >&2
-          exit 1
-        fi
+        main() {
+          validateInputs
+          scanDirectoryTree
+        }
 
-        if [[ -z "${{ inputs.display-lines }}" ]]
-        then
-          echo "❌Missing action input: 'display-lines'!" >&2
-          exit 1
-        fi
-
-        if [[ -z "${{ inputs.verbose }}" ]]
-        then
-          echo "❌Missing action input: 'verbose'!" >&2
-          exit 1
-        fi
-
-    - name: Setup environment variables
-      shell: bash
-      run: echo "todoText=TODO!" >> $GITHUB_ENV
-
-    - name: Scan the directory tree
-      id: scan-directory-tree
-      shell: bash
-      working-directory: ${{ inputs.root-directory }}
-      run: |
-        sourceFileRegex="${{ inputs.source-file-regex }}"
-        displayLines="${{ inputs.display-lines }}"
-        crashOnFound="${{ inputs.crash-on-found }}"
-
-        if [[ "$displayLines" == "true" ]]
-        then
-          quietArg=""
-        else
-          quietArg="-q"
-        fi
-
-        if [[ "${{ inputs.verbose }}" == "true" ]]
-        then
-          echo "🔎File list to filter when looking for TODOs:"
-          find -type f -print
-          echo "🔎🔎🔎"
-        fi
-
-        if find -type f -print0 | grep -zP "${sourceFileRegex}" | xargs -0 grep -Hn $quietArg "$todoText"
-        then
-          found=true
-        else
-          found=false
-        fi
-
-        echo "found=$found" >> $GITHUB_OUTPUT
-
-        if [[ "$found" == "true" ]]
-        then
-          if  [[ "$crashOnFound" == "true" ]]
+        validateInputs() {
+          if [[ -z "${{ inputs.source-file-regex }}" ]]
           then
-            echo "❌Critical TODOs found!" >&2
+            echo "❌Missing action input: 'source-file-regex'!" >&2
             exit 1
           fi
-        else
-          echo "✅No critical TODOs found!"
-        fi
+
+          if [[ -z "${{ inputs.crash-on-found }}" ]]
+          then
+            echo "❌Missing action input: 'crash-on-found'!" >&2
+            exit 1
+          fi
+
+          if [[ -z "${{ inputs.display-lines }}" ]]
+          then
+            echo "❌Missing action input: 'display-lines'!" >&2
+            exit 1
+          fi
+
+          if [[ -z "${{ inputs.verbose }}" ]]
+          then
+            echo "❌Missing action input: 'verbose'!" >&2
+            exit 1
+          fi
+        }
+
+        scanDirectoryTree() {
+          local sourceFileRegex="${{ inputs.source-file-regex }}"
+          echo "📥Source file regex: '$sourceFileRegex'"
+
+          local crashOnFound="${{ inputs.crash-on-found }}"
+          echo "📥Crash on found: $crashOnFound"
+
+          local displayLines="${{ inputs.display-lines }}"
+          echo "📥Display lines: $displayLines"
+
+          local verbose="${{ inputs.verbose }}"
+          echo "📥Verbose: $verbose"
+
+          if [[ "$verbose" == "true" ]]
+          then
+            echo "🔎File list to filter when looking for TODOs:"
+            find -type f -print
+            echo "🔎🔎🔎"
+          fi
+
+          if [[ "$displayLines" == "true" ]]
+          then
+            local quietArg=""
+          else
+            local quietArg="-q"
+          fi
+
+          if find -type f -print0 | grep -zP "$sourceFileRegex" | xargs -0 grep --color=always -Hn $quietArg "$todoText"
+          then
+            local found=true
+          else
+            local found=false
+          fi
+
+          echo "found=$found" >> $GITHUB_OUTPUT
+
+          if [[ "$found" == "true" ]]
+          then
+            if  [[ "$crashOnFound" == "true" ]]
+            then
+              echo "❌Critical TODOs found!" >&2
+              exit 1
+            else
+              echo "⚠️Critical TODOs found!"
+            fi
+          else
+            echo "✅No critical TODOs found!"
+          fi
+        }
+
+        main
diff --git a/actions/generate-wasm-target/action.yml b/actions/generate-wasm-target/action.yml
--- a/actions/generate-wasm-target/action.yml
+++ b/actions/generate-wasm-target/action.yml
@@ -64,86 +64,101 @@ runs:
         echo "📥Target: '$target'"
 
         echo "📥Requested npm-scope: '${{ inputs.npm-scope }}'"
-
         scope="${{ steps.parse-npm-scope.outputs.actual-scope }}"
         echo "🔎Actual npm scope: '$scope'"
 
         development="${{ inputs.development }}"
         echo "📥Development? $development"
 
+        nodejsVersion="${{ inputs.nodejs-version }}"
+        echo "📥NodeJS version: '$nodejsVersion'"
+
+        pnpmVersion="${{ inputs.pnpm-version }}"
+        echo "📥pnpm version: '$pnpmVersion'"
+
         echo "Project directory: '${{ inputs.project-directory }}'"
 
         targetDirectory="${{ inputs.target-directory }}"
         echo "📥Target directory: '$targetDirectory'"
 
-        echo "📦Generating the WebAssembly project files..."
+        main() {
+          generateWebAssemblyTarget
 
-        if [[ "$development" == "true" ]]
-        then
-          modeArg="--dev"
-        else
-          modeArg="--release"
-        fi
+          pushd "$targetDirectory"
 
-        if [[ -n "$scope" ]]
-        then
-          scopeArg="--scope $scope"
-        else
-          scopeArg=""
-        fi
+          if [[ -n "$nodejsVersion" ]]
+          then
+            injectNodeJsVersion
+          fi
 
-        wasm-pack build --target "$target" $modeArg $scopeArg --out-dir "$targetDirectory"
+          if [[ -n "$pnpmVersion" ]]
+          then
+            injectPnpmVersion
+          fi
 
-    - name: Inject the requested NodeJS version into package.json
-      if: ${{ inputs.nodejs-version != '' }}
-      shell: bash
-      working-directory: ${{ inputs.project-directory }}/${{ inputs.target-directory }}
-      run: |
-        if [[ ! -f "package.json" ]]
-        then
-          echo "❌package.json was not generated for this target - cannot inject the requested NodeJS version!"
-          exit 1
-        fi
+          tryToDisplayPackageJson
 
-        nodejsVersion="${{ inputs.nodejs-version }}"
-        echo "🧬Injecting the requested NodeJS version ('$nodejsVersion')..."
+          popd
 
-        tempDescriptor="$(mktemp)"
-        jq '.engines.node = "'"$nodejsVersion"'"' package.json > "$tempDescriptor"
-        mv "$tempDescriptor" package.json
+          echo "✅WebAssembly target ready in '$targetDirectory'!"
+        }
 
-    - name: Inject the requested pnpm version into package.json
-      if: ${{ inputs.pnpm-version != '' }}
-      shell: bash
-      working-directory: ${{ inputs.project-directory }}/${{ inputs.target-directory }}
-      run: |
-        if [[ ! -f "package.json" ]]
-        then
-          echo "❌package.json was not generated for this target - cannot inject the requested pnpm version!"
-          exit 1
-        fi
+        generateWebAssemblyTarget() {
+          echo "📦Generating the WebAssembly project files..."
 
-        pnpmVersion="${{ inputs.pnpm-version }}"
-        echo "🧬Injecting the requested pnpm version ('$pnpmVersion')..."
+          if [[ "$development" == "true" ]]
+          then
+            local modeArg="--dev"
+          else
+            local modeArg="--release"
+          fi
 
-        tempDescriptor="$(mktemp)"
-        jq '.packageManager = "pnpm@'"$pnpmVersion"'"' package.json > "$tempDescriptor"
-        mv "$tempDescriptor" package.json
+          if [[ -n "$scope" ]]
+          then
+            local scopeArg="--scope $scope"
+          else
+            local scopeArg=""
+          fi
 
-    - name: Display the generated package.json descriptor
-      shell: bash
-      working-directory: ${{ inputs.project-directory }}/${{ inputs.target-directory }}
-      run: |
-        if [[ -f "package.json" ]]
-        then
-          echo "📦Generated package.json descriptor for the '${{ inputs.target}}' target:"
-          jq -C '.' package.json
-        else
-          echo "💭No package.json descriptor generated for the '${{ inputs.target}}' target..."
-        fi
+          wasm-pack build --target "$target" $modeArg $scopeArg --out-dir "$targetDirectory"
+        }
 
-    - name: Display success message
-      shell: bash
-      working-directory: ${{ inputs.project-directory }}
-      run: |
-        echo "✅WebAssembly target ready in '${{ inputs.target-directory }}'!"
+        injectNodeJsVersion() {
+          if [[ ! -f "package.json" ]]
+          then
+            echo "❌package.json was not generated for this target - cannot inject the requested NodeJS version!"
+            exit 1
+          fi
+
+          echo "🧬Injecting the requested NodeJS version ('$nodejsVersion')..."
+
+          local tempDescriptor="$(mktemp)"
+          jq '.engines.node = "'"$nodejsVersion"'"' package.json > "$tempDescriptor"
+          mv "$tempDescriptor" package.json
+        }
+
+        injectPnpmVersion() {
+          if [[ ! -f "package.json" ]]
+          then
+            echo "❌package.json was not generated for this target - cannot inject the requested pnpm version!"
+            exit 1
+          fi
+
+          echo "🧬Injecting the requested pnpm version ('$pnpmVersion')..."
+
+          local tempDescriptor="$(mktemp)"
+          jq '.packageManager = "pnpm@'"$pnpmVersion"'"' package.json > "$tempDescriptor"
+          mv "$tempDescriptor" package.json
+        }
+
+        tryToDisplayPackageJson() {
+          if [[ -f "package.json" ]]
+          then
+            echo "📦Generated package.json descriptor for the '$target' target:"
+            jq -C '.' package.json
+          else
+            echo "💭No package.json descriptor generated for the '$target' target..."
+          fi
+        }
+
+        main
diff --git a/actions/install-system-packages/action.yml b/actions/install-system-packages/action.yml
--- a/actions/install-system-packages/action.yml
+++ b/actions/install-system-packages/action.yml
@@ -15,98 +15,100 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Validate inputs
-      shell: bash
+    - shell: bash
       run: |
-        if [[ -z "${{ inputs.packages }}" ]]
-        then
-          echo "❌Missing action input: 'packages'!" >&2
-          exit 1
-        fi
+        main() {
+          validateInputs
 
-        if [[ -z "${{ inputs.initial-update }}" ]]
-        then
-          echo "❌Missing action input: 'initial-update'!" >&2
-          exit 1
-        fi
-
-    - name: Determine whether the packages should be installed
-      shell: bash
-      run: |
-        requiredCommand="${{inputs.required-command}}"
-
-        installPackages=true
-
-        if [[ -n "$requiredCommand" ]]
-        then
-          echo "📥Required command: '$requiredCommand'"
-
-          if type "$requiredCommand" > /dev/null 2>&1
+          if ! shouldRunInstaller
           then
-            echo "✅Required command '$requiredCommand' available - no need to install it!"
-
-            installPackages=false
-          else
-            echo "💫Required command '$requiredCommand' not available - now installing its packages..."
+            exit 0
           fi
 
-        else
-          echo "💫No required command passed - the requested packages will be installed unconditionally"
-        fi
+          if [[ "${{ inputs.initial-update }}" == 'true' ]]
+          then
+            updatePackageList
+          fi
 
-        echo "🔎Install packages? $installPackages"
+          installPackages
+        }
 
-        echo "installPackages=$installPackages" >> $GITHUB_ENV
+        validateInputs() {
+          if [[ -z "${{ inputs.packages }}" ]]
+          then
+            echo "❌Missing action input: 'packages'!" >&2
+            exit 1
+          fi
 
-    - name: Update the package list
-      if: ${{ env.installPackages == 'true' && inputs.initial-update == 'true' }}
-      shell: bash
-      run: |
-        flagFile="$HOME/install-system-packages-updated"
+          if [[ -z "${{ inputs.initial-update }}" ]]
+          then
+            echo "❌Missing action input: 'initial-update'!" >&2
+            exit 1
+          fi
+        }
 
-        if [[ -f "$flagFile" ]]
-        then
-          echo "💡The package list has already been updated!"
-          exit 0
-        fi
+        shouldRunInstaller() {
+          local requiredCommand="${{inputs.required-command}}"
 
-        echo "📥Updating the package list..."
+          if [[ -n "$requiredCommand" ]]
+          then
+            echo "📥Required command: '$requiredCommand'"
 
-        outputFile="$(mktemp)"
+            if type "$requiredCommand" > /dev/null 2>&1
+            then
+              echo "✅Required command '$requiredCommand' available - no need to install it!"
+              return 1
+            else
+              echo "💫Required command '$requiredCommand' not available - now installing its packages..."
+            fi
+          else
+            echo "💫No required command passed - the requested packages will be installed unconditionally"
+          fi
 
-        if ! sudo apt-get update &> "$outputFile"
-        then
-          echo "❌Error while updating the package list! Installer log:"
-          cat "$outputFile"
-          echo "❌❌❌"
+          return 0
+        }
 
-          exit 1
-        fi
+        updatePackageList() {
+          local flagFile="$HOME/install-system-packages-updated"
 
-        touch "$flagFile"
+          if [[ -f "$flagFile" ]]
+          then
+            echo "💡The package list has already been updated!"
+            return 0
+          fi
 
-    - name: Install packages
-      if: ${{ env.installPackages == 'true' }}
-      shell: bash
-      run: |
-        requestedPackages="${{ inputs.packages }}"
+          echo "📥Updating the package list..."
 
-        actualPackages="$(echo "$requestedPackages" | perl -pe 's/[\s,]+/ /g')"
+          runQuietly "sudo apt-get update"
+        }
 
-        echo "📥Requested packages: $actualPackages"
+        runQuietly() {
+          local commandLine="$1"
 
-        outputFile="$(mktemp)"
+          local outputFile="$(mktemp)"
 
-        echo "📦Installing packages..."
+          if ! $commandLine &> "$outputFile"
+          then
+            echo "❌Error while running the command! Log:"
+            cat "$outputFile"
+            echo "❌❌❌"
 
-        if ! sudo apt-get install -y $actualPackages &> "$outputFile"
-        then
-          echo "❌Error while installing the packages! Installer log:"
-          cat "$outputFile"
-          echo "❌❌❌"
+            exit 1
+          fi
+        }
 
-          exit 1
-        fi
+        installPackages() {
+          local requestedPackages="${{ inputs.packages }}"
 
+          echo "📥Requested packages: $requestedPackages"
 
-        echo "✅Packages installed!"
+          local actualPackages="$(echo "$requestedPackages" | perl -pe 's/[\s,]+/ /g')"
+
+          echo "📦Installing packages..."
+
+          runQuietly "sudo apt-get install -y $actualPackages"
+
+          echo "✅Packages installed!"
+        }
+
+        main
diff --git a/actions/install-via-sdkman/action.yml b/actions/install-via-sdkman/action.yml
--- a/actions/install-via-sdkman/action.yml
+++ b/actions/install-via-sdkman/action.yml
@@ -11,70 +11,76 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Validate inputs
-      shell: bash
-      run: |
-        if [[ -z "${{ inputs.candidate }}" ]]
-        then
-          echo "❌Missing action input: 'candidate'!" >&2
-          exit 1
-        fi
-
-        if [[ -z "${{ inputs.version }}" ]]
-        then
-          echo "❌Missing action input: 'version'!" >&2
-          exit 1
-        fi
-
-    - name: Setup environment variables
-      shell: bash
+    - shell: bash
       run: |
         sdkmanHome="$HOME/.sdkman"
 
-        echo "sdkmanHome=$sdkmanHome" >> $GITHUB_ENV
+        validateInputs() {
+          if [[ -z "${{ inputs.candidate }}" ]]
+          then
+            echo "❌Missing action input: 'candidate'!" >&2
+            exit 1
+          fi
 
-    - name: Ensure SDKMAN! is installed
-      shell: bash
-      working-directory: ${{ inputs.project-directory }}
-      run: |
-        if type -t sdk
-        then
-          echo "🚀It seems SDKMAN! is already installed and ready to run!"
-          exit 0
-        fi
+          if [[ -z "${{ inputs.version }}" ]]
+          then
+            echo "❌Missing action input: 'version'!" >&2
+            exit 1
+          fi
+        }
 
-        if [[ -d "$sdkmanHome" ]]
-        then
-          echo "☑It seems that SDKMAN! was previously installed"
-          exit 0
-        fi
+        ensureSdkmanInstalled() {
+          if type -t sdk
+          then
+            echo "🚀It seems SDKMAN! is already installed and ready to run!"
+            return 0
+          fi
 
-        echo "📥Installing SDKMAN!..."
+          if [[ -d "$sdkmanHome" ]]
+          then
+            echo "☑It seems that SDKMAN! was previously installed"
+            return 0
+          fi
 
-        curl -s "https://get.sdkman.io" | bash
+          echo "📥Installing SDKMAN!..."
 
-        echo "🚀SDKMAN installed!"
+          curl -s "https://get.sdkman.io" | bash
 
-    - name: Install the requested candidate
-      shell: bash
-      working-directory: ${{ inputs.project-directory }}
-      run: |
-        candidate="${{ inputs.candidate }}"
-        version="${{ inputs.version }}"
+          echo "🚀SDKMAN installed!"
+        }
 
-        if ! type -t sdk
-        then
-          echo '🚀Setting up SDKMAN!...'
+        ensureSdkmanReady() {
+          if ! type -t sdk
+          then
+            echo '🚀Setting up SDKMAN!...'
 
-          source "$sdkmanHome/bin/sdkman-init.sh"
+            source "$sdkmanHome/bin/sdkman-init.sh"
+          fi
 
           echo "✅SDKMAN! ready!"
-        fi
+        }
 
-        echo "📥Installing $candidate($version)..."
+        installCandidateSdk() {
+          local candidate="${{ inputs.candidate }}"
+          local version="${{ inputs.version }}"
 
-        sdk install "$candidate" "$version"
+          echo "📥Installing $candidate($version)..."
 
-        echo "PATH=$sdkmanHome/candidates/candidate/$version:$PATH" >> $GITHUB_ENV
+          sdk install "$candidate" "$version"
 
-        echo "✅$candidate($version) installed!"
+          echo "PATH=$sdkmanHome/candidates/candidate/$version:$PATH" >> $GITHUB_ENV
+
+          echo "✅$candidate($version) installed!"
+        }
+
+        main() {
+          validateInputs
+
+          ensureSdkmanInstalled
+
+          ensureSdkmanReady
+
+          installCandidateSdk
+        }
+
+        main
diff --git a/actions/run-custom-tests/action.yml b/actions/run-custom-tests/action.yml
--- a/actions/run-custom-tests/action.yml
+++ b/actions/run-custom-tests/action.yml
@@ -23,68 +23,74 @@ runs:
     - name: Detect directory existence
       shell: bash
       run: |
-        if [[ -z "${{ inputs.optional }}" ]]
-        then
-          echo "❌Missing action input: 'optional'!" >&2
-          exit 1
-        fi
+        main() {
+          validateInputs
+          detectTestStrategy
+        }
 
-        if [[ ! -d "${{ inputs.root-directory }}" ]]
-        then
-          if [[ "${{ inputs.optional }}" == "true" ]]
+        validateInputs() {
+          if [[ -z "${{ inputs.optional }}" ]]
           then
-            echo "💭Skipping optional tests in missing directory: '${{ inputs.root-directory }}'"
-            echo "strategy=exit" >> $GITHUB_ENV
-            exit 0
+            echo "❌Missing action input: 'optional'!" >&2
+            exit 1
+          fi
+
+          if [[ -d "${{ inputs.root-directory }}" ]]
+          then
+            cd "${{ inputs.root-directory }}"
           else
-            echo "❌Cannot run custom tests in missing directory: '${{ inputs.root-directory }}'" >&2
-            exit 1
+            if [[ "${{ inputs.optional }}" == "true" ]]
+            then
+              echo "💭Skipping optional tests in missing directory: '${{ inputs.root-directory }}'"
+              echo "strategy=exit" >> $GITHUB_ENV
+              exit 0
+            else
+              echo "❌Cannot run custom tests in missing directory: '${{ inputs.root-directory }}'" >&2
+              exit 1
+            fi
           fi
-        fi
+        }
 
-        echo "strategy=detect" >> $GITHUB_ENV
+        detectTestStrategy() {
+          echo "🔬Detecting custom test strategy in directory '${{ inputs.root-directory }}'..."
 
-    - name: Validate inputs
-      if: ${{ env.strategy == 'detect' }}
-      shell: bash
-      working-directory: ${{ inputs.root-directory }}
-      run: |
-        echo "🔬Detecting custom test strategy in directory '${{ inputs.root-directory }}'..."
+          local scriptFile="${{ inputs.script-file }}"
 
-        scriptFile="${{ inputs.script-file }}"
-
-        if [[ -n "$scriptFile" && -f "$scriptFile" ]]
-        then
-          echo "🐚Custom test script '$scriptFile' found!"
-          strategy="script"
-
-          if [[ -z "${{ inputs.script-shell }}" ]]
+          if [[ -n "$scriptFile" && -f "$scriptFile" ]]
           then
-            echo "❌Missing action input: 'script-shell'!" >&2
-            exit 1
-          fi
-        elif [[ -f "package.json" ]]
-        then
-          echo "📦package.json file found!"
-          strategy="nodejs"
-        elif [[ -f "Cargo.toml" ]]
-        then
-          echo "🦀Cargo.toml file found!"
-          strategy="rust"
-        else
-          if [[ "${{ inputs.optional }}" == "true" ]]
+            echo "🐚Custom test script '$scriptFile' found!"
+            local strategy="script"
+
+            if [[ -z "${{ inputs.script-shell }}" ]]
+            then
+              echo "❌Missing action input: 'script-shell'!" >&2
+              exit 1
+            fi
+          elif [[ -f "package.json" ]]
           then
-            echo "💭No supported strategy detected for the optional custom tests"
-            strategy="exit"
+            echo "📦package.json file found!"
+            local strategy="nodejs"
+          elif [[ -f "Cargo.toml" ]]
+          then
+            echo "🦀Cargo.toml file found!"
+            local strategy="rust"
           else
-            echo "❌Cannot run custom tests: no supported test strategy could be detected!" >&2
-            exit 1
+            if [[ "${{ inputs.optional }}" == "true" ]]
+            then
+              echo "💭No supported strategy detected for the optional custom tests"
+              local strategy="exit"
+            else
+              echo "❌Cannot run custom tests: no supported test strategy could be detected!" >&2
+              exit 1
+            fi
           fi
-        fi
 
-        echo "🔎Test strategy: '$strategy'"
+          echo "🔎Test strategy: '$strategy'"
 
-        echo "strategy=$strategy" >> $GITHUB_ENV
+          echo "strategy=$strategy" >> $GITHUB_ENV
+        }
+
+        main
 
     - name: Run script
       if: ${{ env.strategy == 'script' }}
