Refactor Bash flow for actions:
* `check-rust-versions`

* `check-subpath-exports`

* `extract-rust-snippets`

* `find-critical-todos`

* `generate-wasm-target`

* `inject-subpath-exports`

* `install-system-packages`

* `install-wasm-pack`

* `publish-rust-crate`

* `run-custom-tests`

* `setup-nodejs-context`

* `tag-and-release`

* `upload-release-assets`

* `verify-rust-crate`

diff --git a/actions/check-rust-versions/action.yml b/actions/check-rust-versions/action.yml
--- a/actions/check-rust-versions/action.yml
+++ b/actions/check-rust-versions/action.yml
@@ -9,25 +9,33 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Ensure the toolchain file is present
-      shell: bash
+    - shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
-        toolchainFile="rust-toolchain.toml"
+        main() {
+          checkToolchainFile
+          printToolVersions
+        }
 
-        if [[ ! -f "$toolchainFile" ]]
-        then
-          echo "❌Missing toolchain file: '$toolchainFile'" >&2
-          exit 1
-        fi
+        checkToolchainFile() {
+          local toolchainFile="rust-toolchain.toml"
 
-    - name: Print Rust tool versions
-      shell: bash
-      working-directory: ${{ inputs.project-directory }}
-      run: |
-        echo "🦀Rust toolchain versions:"
-        cargo --version
-        rustc --version
-        cargo fmt --version
-        cargo clippy --version
-        echo "🦀🦀🦀"
+          if [[ -f "$toolchainFile" ]]
+          then
+            echo "✅Toolchain file found: $toolchainFile"
+          else
+            echo "❌Missing toolchain file: '$toolchainFile'" >&2
+            exit 1
+          fi
+        }
+
+        printToolVersions() {
+          echo "🦀Rust toolchain versions:"
+          cargo --version
+          rustc --version
+          cargo fmt --version
+          cargo clippy --version
+          echo "🦀🦀🦀"
+        }
+
+        main
diff --git a/actions/extract-rust-snippets/action.yml b/actions/extract-rust-snippets/action.yml
--- a/actions/extract-rust-snippets/action.yml
+++ b/actions/extract-rust-snippets/action.yml
@@ -17,79 +17,81 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Validate inputs
-      shell: bash
-      working-directory: ${{ inputs.project-directory }}
-      run: |
-        if [[ -z "${{ inputs.markdown-file }}" ]]
-        then
-          echo "❌Missing action input: 'markdown-file'!" >&2
-          exit 1
-        fi
-
-        if [[ ! -f "${{ inputs.markdown-file }}" ]]
-        then
-          echo "❌Missing source Markdown file: '${{ inputs.markdown-file }}'!" >&2
-          exit 1
-        fi
-
-        if [[ -z "${{ inputs.test-filename-prefix }}" ]]
-        then
-          echo "❌Missing action input: 'test-filename-prefix'!" >&2
-          exit 1
-        fi
-
-    - name: Extract the Rust snippets from Markdown file
-      shell: bash
+    - shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
         markdownFile="${{ inputs.markdown-file }}"
         testFileNamePrefix="${{ inputs.test-filename-prefix }}"
 
-        testDirectory=$(dirname "$testFileNamePrefix")
-        echo "📁Creating test directory: '${testDirectory}'"
-        mkdir -p "$testDirectory"
-        echo "✅Directory created!"
-
-        echo "🔁Trying to extract tests from Rust snippets in Markdown..."
-        awk '/```rust/{f="'"$testFileNamePrefix"'" ++n ".rs"; next} /```/{f=""} f{print > f}' "$markdownFile"
-        echo "✅Process completed!"
-
-    - name: Inject the test code into the test files
-      shell: bash
-      working-directory: ${{ inputs.project-directory }}
-      run: |
-        testFileNamePrefix="${{ inputs.test-filename-prefix }}"
-
-        shopt -s nullglob
-
-        for testFile in "$testFileNamePrefix"*.rs
-        do
-          echo -n "🧬Injecting test code into '$testFile'..."
-          cat << EOF >> "$testFile"
-
-        #[test]
-        fn run_code_snippet() {
-          main().unwrap();
+        main() {
+          validateInputs
+          extractSnippetsToFiles
+          injectTestBootstrapCode
+          listGeneratedTestFiles
         }
+
+        validateInputs() {
+          if [[ -z "${{ inputs.markdown-file }}" ]]
+          then
+            echo "❌Missing action input: 'markdown-file'!" >&2
+            exit 1
+          fi
+
+          if [[ ! -f "${{ inputs.markdown-file }}" ]]
+          then
+            echo "❌Missing source Markdown file: '${{ inputs.markdown-file }}'!" >&2
+            exit 1
+          fi
+
+          if [[ -z "${{ inputs.test-filename-prefix }}" ]]
+          then
+            echo "❌Missing action input: 'test-filename-prefix'!" >&2
+            exit 1
+          fi
+        }
+
+        extractSnippetsToFiles() {
+          local testDirectory=$(dirname "$testFileNamePrefix")
+          echo "📁Creating test directory: '${testDirectory}'"
+          mkdir -p "$testDirectory"
+          echo "✅Directory created!"
+
+          echo "🔁Trying to extract tests from Rust snippets in Markdown..."
+          awk '/```rust/{f="'"$testFileNamePrefix"'" ++n ".rs"; next} /```/{f=""} f{print > f}' "$markdownFile"
+          echo "✅Process completed!"
+        }
+
+        injectTestBootstrapCode() {
+          shopt -s nullglob
+
+          local testFile
+          for testFile in "$testFileNamePrefix"*.rs
+          do
+            echo -n "🧬Injecting test code into '$testFile'..."
+            cat << EOF >> "$testFile"
+
+          #[test]
+          fn run_code_snippet() {
+            main().unwrap();
+          }
         EOF
-          echo "✅"
-        done
+            echo "✅"
+          done
+        }
 
-    - name: Display the extracted test files
-      shell: bash
-      working-directory: ${{ inputs.project-directory }}
-      run: |
-        testFileNamePrefix="${{ inputs.test-filename-prefix }}"
-        testDirectory="$(dirname "$testFileNamePrefix")"
+        listGeneratedTestFiles() {
+          local testDirectory="$(dirname "$testFileNamePrefix")"
 
-        testFiles=$(ls -1 "$testFileNamePrefix"*.rs 2>/dev/null || true)
+          local testFiles=$(ls -1 "$testFileNamePrefix"*.rs 2>/dev/null || true)
 
-        if [ -z "$testFiles" ]
-        then
-          echo "💭No test files generated from Rust snippets"
-        else
-          echo "🔎Generated 🦀Rust test files from Markdown snippets:"
-          echo "$testFiles"
-          echo "✅Test files generated successfully!"
-        fi
+          if [ -z "$testFiles" ]
+          then
+            echo "💭No test files generated from Rust snippets"
+          else
+            echo "🔎Generated 🦀Rust test files from Markdown snippets:"
+            echo "$testFiles"
+            echo "✅Test files generated successfully!"
+          fi
+        }
+
+        main
diff --git a/actions/inject-subpath-exports/action.yml b/actions/inject-subpath-exports/action.yml
--- a/actions/inject-subpath-exports/action.yml
+++ b/actions/inject-subpath-exports/action.yml
@@ -17,47 +17,117 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Validate inputs
-      shell: bash
+    - shell: bash
       working-directory: ${{ inputs.project-directory }}
       run: |
-        case "${{ inputs.mode }}" in
-          "prefer-index" | all)
-            ;;
-          *)
-            echo "❌Invalid value for 'mode' input: '${{ inputs.mode }}'!" >&2
+        main() {
+          validateInputs
+          displayInitialExports
+          performInjection
+          displayFinalExports
+        }
+
+        validateInputs() {
+          case "${{ inputs.mode }}" in
+            "prefer-index" | all)
+              ;;
+            *)
+              echo "❌Invalid value for 'mode' input: '${{ inputs.mode }}'!" >&2
+              exit 1
+          esac
+
+          if [[ -z "${{ inputs.source-directory }}" ]]
+          then
+            echo "❌Missing action input: 'source-directory'!" >&2
             exit 1
-        esac
+          fi
 
-        if [[ -z "${{ inputs.source-directory }}" ]]
-        then
-          echo "❌Missing action input: 'source-directory'!" >&2
-          exit 1
-        fi
+          if [[ ! -f "package.json" ]]
+          then
+            echo "❌The package.json descriptor file does not exist!!" >&2
+            exit 1
+          fi
 
-        if [[ ! -f "package.json" ]]
-        then
-          echo "❌The package.json descriptor file does not exist!!" >&2
-          exit 1
-        fi
+          if [[ ! -d "${{ inputs.source-directory }}" ]]
+          then
+            echo "❌Source directory '${{ inputs.source-directory }}' does not exist!" >&2
+            exit 1
+          fi
+        }
 
-        if [[ ! -d "${{ inputs.source-directory }}" ]]
-        then
-          echo "❌Source directory '${{ inputs.source-directory }}' does not exist!" >&2
-          exit 1
-        fi
+        displayInitialExports() {
+          echo "📦package.json exports at the beginning of inject-subpath-exports:"
+          jq -C .exports package.json
+        }
 
-    - name: Display initial status of the exports
-      shell: bash
-      working-directory: ${{ inputs.project-directory }}
-      run: |
-        echo "📦package.json exports at the beginning of inject-subpath-exports:"
-        jq -C .exports package.json
+        performInjection() {
+          local mode="${{ inputs.mode }}"
+          local sourceDirectory="${{ inputs.source-directory }}"
 
-    - name: Generate and inject subpath exports
-      shell: bash
-      working-directory: ${{ inputs.project-directory }}
-      run: |
+          local rootIndexNames=("index.ts" "index.js")
+
+          local rootIndexName
+          for rootIndexName in ${rootIndexNames[@]}
+          do
+            local potentialRootIndex="$sourceDirectory/$rootIndexName"
+
+            echo "🔎Looking for potential root index: '${potentialRootIndex}'"
+
+            if [[ -f "$potentialRootIndex" ]]
+            then
+              local rootIndex="$potentialRootIndex"
+              break
+            fi
+          done
+
+          if [[ -n "$rootIndex" ]]
+          then
+            echo "✅Root index file found: '$rootIndex'!"
+
+            updatePackageJson "$(cat <<EOF
+              .exports += {
+                ".": {
+                  types: "./dist/index.d.ts",
+                  import: "./dist/index.js"
+                }
+              }
+        EOF
+            )"
+
+            if [[ "$mode" == "prefer-index" ]]
+            then
+              echo "🐹In this mode, since the root index has been found, no more subpath exports will be injected"
+
+              return 0
+            fi
+          else
+            echo "💭No root index file found..."
+          fi
+
+          find "$sourceDirectory" -mindepth 2 -maxdepth 2 -type f -regex '.*/index\.\(t\|j\)s' | sort | while IFS= read -r subIndexFile
+          do
+            local exportName="$(dirname "$subIndexFile" | xargs basename)"
+
+            local distExportDirectory="./dist/$exportName"
+
+            echo "✅Export '${exportName}' provided by dist directory: '${distExportDirectory}'"
+
+            local declarationsFile="${distExportDirectory}/index.d.ts"
+
+            local esmFile="${distExportDirectory}/index.js"
+
+            updatePackageJson "$(cat <<EOF
+              .exports += {
+                "./$exportName": {
+                  types: "$declarationsFile",
+                  import: "$esmFile"
+                }
+              }
+        EOF
+            )"
+          done
+        }
+
         updatePackageJson() {
           local updatingExpression="$1"
 
@@ -67,74 +137,9 @@ runs:
           mv "$tempPackage" package.json
         }
 
-        mode="${{ inputs.mode }}"
-        sourceDirectory="${{ inputs.source-directory }}"
+        displayFinalExports() {
+          echo "📦package.json exports at the end of inject-subpath-exports:"
+          jq -C .exports package.json
+        }
 
-        rootIndexNames=("index.ts" "index.js")
-
-        for rootIndexName in ${rootIndexNames[@]}
-        do
-          potentialRootIndex="$sourceDirectory/$rootIndexName"
-
-          echo "🔎Looking for potential root index: '${potentialRootIndex}'"
-
-          if [[ -f "$potentialRootIndex" ]]
-          then
-            rootIndex="$potentialRootIndex"
-            break
-          fi
-        done
-
-        if [[ -n "$rootIndex" ]]
-        then
-          echo "✅Root index file found: '$rootIndex'!"
-
-          updatePackageJson "$(cat <<EOF
-            .exports += {
-              ".": {
-                types: "./dist/index.d.ts",
-                import: "./dist/index.js"
-              }
-            }
-        EOF
-          )"
-
-          if [[ "$mode" == "prefer-index" ]]
-          then
-            echo "🐹In this mode, since the root index has been found, no more subpath exports will be injected"
-
-            exit 0
-          fi
-        else
-          echo "💭No root index file found..."
-        fi
-
-        find "$sourceDirectory" -mindepth 2 -maxdepth 2 -type f -regex '.*/index\.\(t\|j\)s' | sort | while IFS= read -r subIndexFile
-        do
-          exportName="$(dirname "$subIndexFile" | xargs basename)"
-
-          distExportDirectory="./dist/$exportName"
-
-          echo "✅Export '${exportName}' provided by dist directory: '${distExportDirectory}'"
-
-          declarationsFile="${distExportDirectory}/index.d.ts"
-
-          esmFile="${distExportDirectory}/index.js"
-
-          updatePackageJson "$(cat <<EOF
-            .exports += {
-              "./$exportName": {
-                types: "$declarationsFile",
-                import: "$esmFile"
-              }
-            }
-        EOF
-          )"
-        done
-
-    - name: Display final status of the exports
-      shell: bash
-      working-directory: ${{ inputs.project-directory }}
-      run: |
-        echo "📦package.json exports at the end of inject-subpath-exports:"
-        jq -C .exports package.json
+        main
diff --git a/actions/install-wasm-pack/action.yml b/actions/install-wasm-pack/action.yml
--- a/actions/install-wasm-pack/action.yml
+++ b/actions/install-wasm-pack/action.yml
@@ -8,30 +8,38 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Validate inputs
-      shell: bash
+    - shell: bash
       run: |
-        if [[ -z "${{ inputs.wasm-pack-version }}" ]]
-        then
-          echo "❌Missing action input: 'wasm-pack-version'!" >&2
-          exit 1
-        fi
+        main() {
+          validateInputs
+          installWasmPack
+          printWasmPackVersion
+        }
 
-    - name: Install pnpm
-      uses: pnpm/action-setup@v4
-      with:
-        version: 9
+        validateInputs() {
+          if [[ -z "${{ inputs.wasm-pack-version }}" ]]
+          then
+            echo "❌Missing action input: 'wasm-pack-version'!" >&2
+            exit 1
+          fi
+        }
 
-    - name: Install wasm-pack via pnpm
-      shell: bash
-      run: |
-        echo "🌐Installing wasm-pack ${{ inputs.wasm-pack-version }}..."
-        pnpm add -g "wasm-pack@${{ inputs.wasm-pack-version }}"
-        echo "✅wasm-pack installed!"
+        installWasmPack() {
+          local requestedVersion="${{ inputs.wasm-pack-version }}"
 
-    - name: Print wasm-pack version
-      shell: bash
-      run: |
-        echo "🔎Now ensuring wasm-pack is available..."
-        wasm-pack --version
-        echo "✅wasm-pack ready!"
+          echo "🌐Installing wasm-pack $requestedVersion..."
+
+          npm install -g "wasm-pack@$requestedVersion"
+
+          echo "✅wasm-pack installed!"
+        }
+
+        printWasmPackVersion() {
+          echo "🔎Now ensuring wasm-pack is available..."
+
+          wasm-pack --version
+
+          echo "✅wasm-pack ready!"
+        }
+
+        main
diff --git a/actions/upload-release-assets/action.yml b/actions/upload-release-assets/action.yml
--- a/actions/upload-release-assets/action.yml
+++ b/actions/upload-release-assets/action.yml
@@ -19,39 +19,45 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Validate inputs
-      shell: bash
+    - shell: bash
       working-directory: ${{ inputs.source-directory }}
       run: |
-        if [[ -z "${{ inputs.release-tag }}" ]]
-        then
-          echo "❌Missing action input: 'release-tag'!" >&2
-          exit 1
-        fi
+        main() {
+          validateInputs
+          publishReleaseAssets
+        }
 
-        if [[ -z "${{ inputs.files }}" ]]
-        then
-          echo "❌Missing action input: 'files'!" >&2
-          exit 1
-        fi
+        validateInputs() {
+          if [[ -z "${{ inputs.release-tag }}" ]]
+          then
+            echo "❌Missing action input: 'release-tag'!" >&2
+            exit 1
+          fi
 
-        if [[ -z "${{ inputs.overwrite }}" ]]
-        then
-          echo "❌Missing action input: 'overwrite'!" >&2
-          exit 1
-        fi
+          if [[ -z "${{ inputs.files }}" ]]
+          then
+            echo "❌Missing action input: 'files'!" >&2
+            exit 1
+          fi
 
-    - name: Publish release assets
-      shell: bash
-      working-directory: ${{ inputs.source-directory }}
-      run: |
-        if [[ "${{ inputs.overwrite}}" == "true" ]]
-        then
-          flags="--clobber"
-        else
-          flags=""
-        fi
+          if [[ -z "${{ inputs.overwrite }}" ]]
+          then
+            echo "❌Missing action input: 'overwrite'!" >&2
+            exit 1
+          fi
+        }
 
-        gh release upload "$flags" "${{ inputs.release-tag }}" ${{ inputs.files }}
+        publishReleaseAssets() {
+          if [[ "${{ inputs.overwrite }}" == "true" ]]
+          then
+            local clobberArg="--clobber"
+          else
+            local clobberArg=""
+          fi
+
+          gh release upload $clobberArg "${{ inputs.release-tag }}" ${{ inputs.files }}
+        }
+
+        main
       env:
         GH_TOKEN: ${{ github.token }}
