Verify that wasm-pack-version is actually passed

diff --git a/actions/install-wasm-pack/action.yml b/actions/install-wasm-pack/action.yml
--- a/actions/install-wasm-pack/action.yml
+++ b/actions/install-wasm-pack/action.yml
@@ -14,6 +14,15 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Validate parameters
+      shell: ${{ inputs.shell }}
+      run: |
+        if [[ -z "${{ inputs.wasm-pack-version }}" ]]
+        then
+          echo "Missing action input: 'wasm-pack-version'!" >&2
+          exit 1
+        fi
+
     - name: Install pnpm
       uses: pnpm/action-setup@v4
       with:
