Introduce version 3.0 (#8)
* Introduce find-critical-todos (closes #4)

* Introduce extract-rust-snippets (closes #7)

* Introduce parse-npm-scope (closes #9)

* Build Rustdoc documentation when verifying Rust crates

* Improve input checks and documentation

diff --git a/actions/install-wasm-pack/action.yml b/actions/install-wasm-pack/action.yml
--- a/actions/install-wasm-pack/action.yml
+++ b/actions/install-wasm-pack/action.yml
@@ -14,12 +14,12 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Validate parameters
+    - name: Validate inputs
       shell: ${{ inputs.shell }}
       run: |
         if [[ -z "${{ inputs.wasm-pack-version }}" ]]
         then
-          echo "Missing action input: 'wasm-pack-version'!" >&2
+          echo "❌Missing action input: 'wasm-pack-version'!" >&2
           exit 1
         fi
 
diff --git a/actions/publish-npm-package/action.yml b/actions/publish-npm-package/action.yml
--- a/actions/publish-npm-package/action.yml
+++ b/actions/publish-npm-package/action.yml
@@ -2,14 +2,14 @@ name: Publish npm package
 description: Publishes a NodeJS package to the npm registry.
 
 inputs:
-  npm-token:
-    description: The secret token for publishing to npm.
-    required: true
-
   dry-run:
     description: Run a simulated publication via --dry-run.
     required: false
     default: false
+    
+  npm-token:
+    description: The secret token for publishing to npm.
+    required: true  
 
   frozen-lockfile:
     description: Fail if 'pnpm-lock.yaml' is missing or outdated.
@@ -29,6 +29,27 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: ${{ inputs.shell }}
+      run: |
+        if [[ -z "${{ inputs.dry-run }}" ]]
+        then
+          echo "❌Missing action input: 'dry-run'!" >&2
+          exit 1
+        fi
+
+        if [[ ${{ inputs.dry-run }} != 'true' && -z "${{ inputs.npm-token }}" ]]
+        then
+          echo "❌Missing action input: 'npm-token'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.frozen-lockfile }}" ]]
+        then
+          echo "❌Missing action input: 'frozen-lockfile'!" >&2
+          exit 1
+        fi
+
     - name: Setup NodeJS and NPM registry
       uses: actions/setup-node@v4
       with:
diff --git a/actions/publish-rust-wasm/action.yml b/actions/publish-rust-wasm/action.yml
--- a/actions/publish-rust-wasm/action.yml
+++ b/actions/publish-rust-wasm/action.yml
@@ -2,6 +2,11 @@ name: Publish Rust web assembly
 description: Publishes a Rust web assembly to the npm registry.
 
 inputs:
+  dry-run:
+    description: Run a simulated publication via --dry-run.
+    required: false
+    default: false
+
   npm-token:
     description: The secret token for publishing to npm.
     required: true
@@ -11,13 +16,8 @@ inputs:
     required: true
 
   npm-scope:
-    description: The npm package scope (without the initial @) or empty.
+    description: The npm package scope or "<ROOT>".
     required: true
-
-  dry-run:
-    description: Run a simulated publication via --dry-run.
-    required: false
-    default: false
 
   wasm-target:
     description: The target of the 'wasm-pack build' command.
@@ -42,8 +42,47 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: ${{ inputs.shell }}
+      run: |
+        if [[ -z "${{ inputs.dry-run }}" ]]
+        then
+          echo "❌Missing action input: 'dry-run'!" >&2
+          exit 1
+        fi
+        
+        if [[ ${{ inputs.dry-run }} != 'true' && -z "${{ inputs.npm-token }}" ]]
+        then
+          echo "❌Missing action input: 'npm-token'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.wasm-pack-version }}" ]]
+        then
+          echo "❌Missing action input: 'wasm-pack-version'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.wasm-target }}" ]]
+        then
+          echo "❌Missing action input: 'wasm-target'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.node-version-directory }}" ]]
+        then
+          echo "❌Missing action input: 'node-version-directory'!" >&2
+          exit 1
+        fi
+
+    - name: Parse npm scope
+      id: parse-npm-scope
+      uses: giancosta86/aurora-github/actions/parse-npm-scope@v3.0.0
+      with:
+        scope: ${{ inputs.npm-scope }}
+
     - name: Install wasm-pack
-      uses: giancosta86/aurora-github/actions/install-wasm-pack@v2.0.1
+      uses: giancosta86/aurora-github/actions/install-wasm-pack@v3.0.0
       with:
         wasm-pack-version: ${{ inputs.wasm-pack-version }}
         shell: ${{ inputs.shell }}
@@ -52,13 +91,13 @@ runs:
       shell: ${{ inputs.shell }}
       working-directory: ${{ inputs.project-directory }}
       run: |
-        scope="${{ inputs.npm-scope }}"
+        scope="${{ steps.parse-npm-scope.outputs.actual-scope }}"
 
-        if [[ ! -z "$scope" ]]
+        if [[ -z "$scope" ]]
         then
-          wasm-pack build --release --target "${{ inputs.wasm-target }}" --scope "${{ inputs.npm-scope }}"
-        else
           wasm-pack build --release --target "${{ inputs.wasm-target }}"
+        else
+          wasm-pack build --release --target "${{ inputs.wasm-target }}" --scope "$scope"
         fi
 
     - name: Copy .nvmrc to the generated NodeJS package
@@ -67,7 +106,7 @@ runs:
       run: cp "${{ inputs.node-version-directory }}/.nvmrc" pkg
 
     - name: Publish NodeJS package
-      uses: giancosta86/aurora-github/actions/publish-npm-package@v2.0.1
+      uses: giancosta86/aurora-github/actions/publish-npm-package@v3.0.0
       with:
         frozen-lockfile: false
         npm-token: ${{ inputs.npm-token }}
diff --git a/actions/verify-rust-crate/action.yml b/actions/verify-rust-crate/action.yml
--- a/actions/verify-rust-crate/action.yml
+++ b/actions/verify-rust-crate/action.yml
@@ -7,6 +7,21 @@ inputs:
     required: false
     default: true
 
+  check-rustdoc:
+    description: Build the documentation - with warnings as errors.
+    required: false
+    default: true
+
+  crash-on-critical-todos:
+    description: Crash the workflow if critical TODOs are found.
+    required: false
+    default: true
+
+  source-file-regex:
+    description: PCRE pattern describing the source files.
+    required: false
+    default: '\.rs$'
+
   check-artifact-version:
     description: Ensure the version in Cargo.toml matches the branch name.
     required: false
@@ -25,17 +40,60 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: ${{ inputs.shell }}
+      working-directory: ${{ inputs.root-directory }}
+      run: |
+        if [[ -z "${{ inputs.run-clippy-checks }}" ]]
+        then
+          echo "❌Missing action input: 'run-clippy-checks'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.check-rustdoc }}" ]]
+        then
+          echo "❌Missing action input: 'check-rustdoc'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.crash-on-critical-todos }}" ]]
+        then
+          echo "❌Missing action input: 'crash-on-critical-todos'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.source-file-regex }}" ]]
+        then
+          echo "❌Missing action input: 'source-file-regex'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.check-artifact-version }}" ]]
+        then
+          echo "❌Missing action input: 'check-artifact-version'!" >&2
+          exit 1
+        fi
+
     - name: Check artifact version
       if: ${{ inputs.check-artifact-version == 'true' }}
-      uses: giancosta86/aurora-github/actions/check-artifact-version@v2.0.1
+      uses: giancosta86/aurora-github/actions/check-artifact-version@v3.0.0
       with:
         project-directory: ${{ inputs.project-directory }}
         shell: ${{ inputs.shell }}
 
     - name: Check Rust versions
-      uses: giancosta86/aurora-github/actions/check-rust-versions@v2.0.1
+      uses: giancosta86/aurora-github/actions/check-rust-versions@v3.0.0
       with:
         project-directory: ${{ inputs.project-directory }}
+        shell: ${{ inputs.shell }}
+
+    - name: Check for critical TODOs
+      uses: giancosta86/aurora-github/actions/find-critical-todos@v3.0.0
+      with:
+        source-file-regex: ${{ inputs.source-file-regex }}
+        crash-on-found: ${{ inputs.crash-on-critical-todos }}
+        display-lines: true
+        root-directory: ${{ inputs.project-directory }}
         shell: ${{ inputs.shell }}
 
     - name: Check format style
@@ -49,6 +107,29 @@ runs:
       working-directory: ${{ inputs.project-directory }}
       run: cargo clippy --all-targets --all-features -- -D warnings
 
+    - name: Check if README.md exists
+      id: detect-readme
+      shell: ${{ inputs.shell }}
+      working-directory: ${{ inputs.project-directory }}
+      run: |
+        if [[ -f "README.md" ]] 
+        then
+          echo "🗒️README.md found! Trying to extract snippets!"
+          readmeExists=true
+        else
+          echo "💭README.md not found - unable to extract snippets."
+          readmeExists=false
+        fi
+
+        echo "readme-exists=$readmeExists" >> $GITHUB_OUTPUT
+
+    - name: Extract code snippets as tests from README.md
+      if: ${{ steps.detect-readme.outputs.readme-exists == 'true' }}
+      uses: giancosta86/aurora-github/actions/extract-rust-snippets@v3.0.0
+      with:
+        project-directory: ${{ inputs.project-directory }}
+        shell: ${{ inputs.shell }}
+
     - name: Run vanilla (no features) tests
       shell: ${{ inputs.shell }}
       working-directory: ${{ inputs.project-directory }}
@@ -58,3 +139,9 @@ runs:
       shell: ${{ inputs.shell }}
       working-directory: ${{ inputs.project-directory }}
       run: cargo test --all-features
+
+    - name: Run documentation checks - with warnings as errors
+      if: ${{ inputs.check-rustdoc == 'true' }}
+      shell: ${{ inputs.shell }}
+      working-directory: ${{ inputs.project-directory }}
+      run: RUSTDOCFLAGS="-D warnings" cargo doc --all-features
diff --git a/actions/verify-rust-wasm/action.yml b/actions/verify-rust-wasm/action.yml
--- a/actions/verify-rust-wasm/action.yml
+++ b/actions/verify-rust-wasm/action.yml
@@ -7,7 +7,7 @@ inputs:
     required: true
 
   npm-scope:
-    description: The npm package scope (without the initial @) - or empty.
+    description: The npm package scope or "<ROOT>".
     required: true
 
   client-tests-directory:
@@ -24,6 +24,21 @@ inputs:
     description: Enable linting via Clippy.
     required: false
     default: true
+
+  check-rustdoc:
+    description: Build the documentation - with warnings as errors.
+    required: false
+    default: false
+
+  crash-on-critical-todos:
+    description: Crash the workflow if critical TODOs are found.
+    required: false
+    default: true
+
+  source-file-regex:
+    description: PCRE pattern describing the source files.
+    required: false
+    default: '\.rs$'
 
   check-artifact-version:
     description: Ensure the version in Cargo.toml matches the branch name.
@@ -43,16 +58,71 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: ${{ inputs.shell }}
+      working-directory: ${{ inputs.root-directory }}
+      run: |
+        if [[ -z "${{ inputs.wasm-pack-version }}" ]]
+        then
+          echo "❌Missing action input: 'wasm-pack-version'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.wasm-target }}" ]]
+        then
+          echo "❌Missing action input: 'wasm-target'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.run-clippy-checks }}" ]]
+        then
+          echo "❌Missing action input: 'run-clippy-checks'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.check-rustdoc }}" ]]
+        then
+          echo "❌Missing action input: 'check-rustdoc'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.crash-on-critical-todos }}" ]]
+        then
+          echo "❌Missing action input: 'crash-on-critical-todos'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.source-file-regex }}" ]]
+        then
+          echo "❌Missing action input: 'source-file-regex'!" >&2
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.check-artifact-version }}" ]]
+        then
+          echo "❌Missing action input: 'check-artifact-version'!" >&2
+          exit 1
+        fi
+    
+    - name: Parse npm scope
+      id: parse-npm-scope
+      uses: giancosta86/aurora-github/actions/parse-npm-scope@v3.0.0
+      with:
+        scope: ${{ inputs.npm-scope }}
+
     - name: Install wasm-pack
-      uses: giancosta86/aurora-github/actions/install-wasm-pack@v2.0.1
+      uses: giancosta86/aurora-github/actions/install-wasm-pack@v3.0.0
       with:
         wasm-pack-version: ${{ inputs.wasm-pack-version }}
         shell: ${{ inputs.shell }}
 
     - name: Verify Rust source files
-      uses: giancosta86/aurora-github/actions/verify-rust-crate@v2.0.1
+      uses: giancosta86/aurora-github/actions/verify-rust-crate@v3.0.0
       with:
         run-clippy-checks: ${{ inputs.run-clippy-checks }}
+        check-rustdoc: ${{ inputs.check-rustdoc }}
+        crash-on-critical-todos: ${{ inputs.crash-on-critical-todos }}
+        source-file-regex: ${{ inputs.source-file-regex }}
         check-artifact-version: ${{ inputs.check-artifact-version }}
         project-directory: ${{ inputs.project-directory }}
         shell: ${{ inputs.shell }}
@@ -66,13 +136,13 @@ runs:
       shell: ${{ inputs.shell }}
       working-directory: ${{ inputs.project-directory }}
       run: |
-        scope="${{ inputs.npm-scope }}"
+        scope="${{ steps.parse-npm-scope.outputs.actual-scope }}"
 
-        if [[ ! -z "$scope" ]]
+        if [[ -z "$scope" ]]
         then
-          wasm-pack build --dev --target "${{ inputs.wasm-target }}" --scope "$scope"
+          wasm-pack build --dev --target "${{ inputs.wasm-target }}"          
         else
-          wasm-pack build --dev --target "${{ inputs.wasm-target }}"
+          wasm-pack build --dev --target "${{ inputs.wasm-target }}" --scope "$scope"
         fi
 
     - name: Ensure test client directory exists
