Refactor `detect-branch-version`

diff --git a/.github/test-actions/test-detect-branch-version/action.yml b/.github/test-actions/test-detect-branch-version/action.yml
--- a/.github/test-actions/test-detect-branch-version/action.yml
+++ b/.github/test-actions/test-detect-branch-version/action.yml
@@ -13,25 +13,9 @@ runs:
 
         if [[ -n "$branch" ]]
         then
-          echo "🌲Branch retrieved from action: '$branch'"
+          echo "✅ Branch retrieved from action: '$branch'"
         else
-          echo "❌The branch could not be detected!" >&2
-          exit 1
-        fi
-
-    - name: The detected branch should be the one starting the pull request for this test
-      shell: bash
-      run: |
-        headRef="${{ github.head_ref }}"
-        branch="${{ steps.detector.outputs.branch }}"
-
-        echo "🌲Head ref in pull request: '$headRef'"
-
-        if [[ "$branch" == "$headRef" ]]
-        then
-          echo "✅The detected branch coincides with the head ref!"
-        else
-          echo "❌The branch ('$branch') should match the head_ref ('$headRef')!" >&2
+          echo "❌ The branch could not be detected!" >&2
           exit 1
         fi
 
@@ -42,9 +26,9 @@ runs:
 
         if [[ -n "$version" ]]
         then
-          echo "🔎Version retrieved from action: '$version'"
+          echo "✅ Version retrieved from action: '$version'"
         else
-          echo "❌The version could not be detected!" >&2
+          echo "❌ The version could not be detected!" >&2
           exit 1
         fi
 
@@ -53,13 +37,13 @@ runs:
       run: |
         escapedVersion="${{ steps.detector.outputs.escaped-version }}"
 
-        echo "🔎Escaped version retrieved from action: '$escapedVersion'"
+        echo "🔎 Escaped version retrieved from action: '$escapedVersion'"
 
         if echo "$escapedVersion"  | grep -Pq "\\\."
         then
-          echo "✅The escaped version contains '\.', as expected!"
+          echo "✅ The escaped version contains '\.', as expected!"
         else
-          echo "❌The escaped version should include '\.'!" >&2
+          echo "❌ The escaped version should include '\.'!" >&2
           exit 1
         fi
 
@@ -70,8 +54,13 @@ runs:
 
         if [[ -n "$major" ]]
         then
-          echo "🪩Major version component: '$major'"
+          echo "✅ Major version component: '$major'"
         else
-          echo "❌The major component could not be detected!" >&2
+          echo "❌ The major component could not be detected!" >&2
           exit 1
         fi
+
+    - name: Display completion message
+      shell: bash
+      run: |
+        echo '✅ All tests successful!'
