Add check on branch name

diff --git a/actions/tag-and-release/action.yml b/actions/tag-and-release/action.yml
--- a/actions/tag-and-release/action.yml
+++ b/actions/tag-and-release/action.yml
@@ -25,7 +25,14 @@ runs:
       shell: ${{ inputs.shell }}
       run: |
         branch="${{ github.head_ref }}"
-        echo "Detected branch: '$branch'"        
+        echo "Detected branch: '$branch'"      
+
+        if [[ ! $branch =~ ^b?[0-9](\.[0-9](\.[0-9])?)?$ ]]
+        then
+          echo "Invalid semver branch format: '$branch'"
+          exit 1
+        fi
+
         echo "branch=$branch" >> $GITHUB_OUTPUT
 
     - name: Detect version from branch
